box/box-content-preview

README.md
Also try triggering public TravisCI build with this PR
=> Docs: Update project status badge

.travis.yml
Following https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda to build PRs and merges to master
=> Chore: Update .travis.yml to build PRs and merges to master

.travis.yml, README.md
- Remove config that only builds master branch - this ends up skipping our PRs
- Update Travis shield.io badge link
=> Chore: Update Travis config

build/karma.conf.js, src/lib/__tests__/util-test.js, src/lib/util.js, src/lib/viewers/text/TextLoader.js, src/lib/viewers/text/__tests__/TextLoader-test.js
Render Vera-protected files instead of displaying the raw HTML.
=> Update: Render Vera-protected HTML files

src/lib/viewers/media/MediaLoader.js
These are now supported like all other videos in Box
=> New: Add ts and flv formats to MediaLoader.js

.github/ISSUE_TEMPLATE.md
GitHub supports issue templates, see https://github.com/blog/2111-issue-and-pull-request-templates
=> Docs: Add issue reporting template

src/lib/annotations/AnnotationDialog.js, src/lib/annotations/AnnotationService.js, src/lib/annotations/__tests__/annotatorUtil-test.js, src/lib/annotations/annotatorUtil.js, src/lib/annotations/doc/DocHighlightDialog.js, src/lib/annotations/doc/__tests__/DocHighlightDialog-test.js
- Removing any reference to files/methods in preview.js
=> Chore: Duplicating any util.js methods used into annotatorUtil.js

src/lib/viewers/media/MediaControls.html, src/lib/viewers/media/Settings.js, src/lib/viewers/media/__tests__/Settings-test.html, src/lib/viewers/media/__tests__/Settings-test.js
Small accessibility improvement
https://www.w3.org/TR/wai-aria-practices/examples/button/button.html
=> Update: Add aria-pressed setting for CC button

src/lib/Preview.js, src/lib/PreviewUI.js, src/lib/__tests__/Preview-test.js, src/lib/__tests__/PreviewUI-test.js, src/lib/annotations/Annotator.js, src/lib/annotations/__tests__/Annotator-test.js, src/lib/annotations/image/ImageAnnotator.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/__tests__/BaseViewer-test.js
- This will allow us to display other types of notifications should we have the need
=> Chore: Initializing notifications in viewer rather than annotator

src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/image/MultiImage.scss, src/lib/viewers/image/__tests__/ImageViewer-test.js
- Updated some comments as well
=> Chore: Cleaning up remaining annotations references outside BaseViewer

src/lib/Browser.js, src/lib/__tests__/Browser-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Should fix https://github.com/mozilla/pdf.js/issues/8700 and https://cloud.box.com/s/xd92oda655j808n0zvklga0qt2tltn6v on Safari
=> Fix: Safari font rendering issue

src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
This enables rendering of content within interactive forms
=> New: Turn on rendering of interactive forms

src/lib/annotations/AnnotationDialog.js, src/lib/annotations/Annotator.scss, src/lib/annotations/__tests__/AnnotationDialog-test.js, src/lib/annotations/doc/DocHighlightDialog.js, src/lib/annotations/doc/DocPointDialog.js, src/lib/annotations/doc/__tests__/DocHighlightDialog-test.js, src/lib/annotations/doc/__tests__/DocPointDialog-test.js, src/lib/annotations/doc/__tests__/docAnnotatorUtil-test.js, src/lib/annotations/doc/docAnnotatorUtil.js, src/lib/annotations/image/ImagePointDialog.js, src/lib/annotations/image/__tests__/ImagePointDialog-test.js
=> New: Flip point annotation dialog if in lower half of file

src/lib/annotations/Annotator.js, src/lib/annotations/__tests__/Annotator-test.js
=> Fix: disableAnnotationMode cannot be called on disallowed modes

src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Revoke object URL during viewer cleanup.
=> Fix: Document print in Chrome

src/lib/viewers/image/ImageBaseViewer.js, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageBaseViewer-test.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
This reverts commit 8f1cc35be9de6f2608d6934522504be53365c86b.
=> Revert "Fix: Only call setOriginalImageSize() on single page images (#394)"

src/lib/annotations/Annotator.js, src/lib/annotations/Annotator.scss, src/lib/annotations/__tests__/Annotator-test.js, src/lib/annotations/annotationConstants.js, src/lib/annotations/doc/CreateHighlightDialog.js, src/lib/annotations/doc/DocAnnotator.js, src/lib/annotations/doc/__tests__/CreateHighlightDialog-test.html, src/lib/annotations/doc/__tests__/CreateHighlightDialog-test.js, src/lib/annotations/doc/__tests__/DocAnnotator-test.js, src/lib/annotations/drawing/DrawingModeController.js, src/lib/annotations/drawing/__tests__/DrawingModeController-test.js
* Fixes selection on Firefox/Safari
* Fixes interaction between text selection and drawings
* Replaces text cursor with crosshair
=> Fix: Fix draw selection and related bugs

src/lib/Preview.js
=> Fix: Bind download function in Preview.js

package.json, yarn.lock
=> Update: box-annotations to v0.5.1

package.json, yarn.lock
=> Update: box-annotations to v0.6.0

package.json, yarn.lock
=> Update: box-annotations to v0.7.0

package.json, yarn.lock
=> Update: box-annotations to v0.7.1

src/lib/viewers/media/DashViewer.js, src/lib/viewers/media/__tests__/DashViewer-test.js
Committing for @bhh1988 since Travis is not running his jobs.
=> Fix: Rename "watermark-cache" query param to "watermark_content"

package.json, yarn.lock
=> Update: box-annotations to v0.7.2

package.json, yarn.lock
=> Update: box-annotations to v0.7.3

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.8.0
=> Update: box-annotations to v0.8.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.8.1
=> Update: box-annotations to v0.8.1

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.9.0
=> Update: box-annotations to v0.9.0

README.md, src/lib/Preview.js, src/lib/__tests__/Preview-test.js, src/lib/__tests__/util-test.js, src/lib/util.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/__tests__/BaseViewer-test.js, src/lib/viewers/box3d/image360/README.md, src/lib/viewers/box3d/model3d/README.md, src/lib/viewers/doc/README.md, src/lib/viewers/image/README.md, src/lib/viewers/media/README.md, src/lib/viewers/swf/README.md, src/lib/viewers/text/README.md
=> Fix: Temporarily disable requireJS if specified to load 3rd party deps

src/lib/PreviewUI.js, src/lib/__tests__/PreviewUI-test.js, src/lib/_navigation.scss, src/lib/constants.js, src/lib/viewers/media/MP3.scss
=> Fix: mobile audio controls overlap with navigation

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.10.0
=> Update: box-annotations to v0.10.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.11.0
=> Update: box-annotations to v0.11.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.11.1
=> Update: box-annotations to v0.11.1

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.12.0
=> Update: box-annotations to v0.12.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.13.0
=> Update: box-annotations to v0.13.0

src/lib/RepStatus.js, src/lib/__tests__/RepStatus-test.js, src/lib/viewers/BaseViewer.js
This will go into patch release 1.30.1
=> Chore: pass file id to RepStatus for easier timers

.travis.yml
Reverts box/box-content-preview#664
=> Revert "Chore: modify email for travis notifications"

CHANGELOG.md, README.md, package.json
This reverts commit 18add250324e33d74f9b184a6ed294aefbf59292.
=> Revert "Release: 1.32.0"

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.14.0
=> Update: box-annotations to v0.14.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.15.0
=> Update: box-annotations to v0.15.0

codecept.conf.js, functional-tests/eventHooks.js, package.json, yarn.lock
This adds job status reporting to saucelabs so it will be visible on the saucelabs dashboard if jobs and builds were successful or failed
=> Chore: update status for jobs in saucelabs

src/lib/events.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/media/DashViewer.js, src/lib/viewers/media/MediaBaseViewer.js, src/lib/viewers/media/__tests__/DashViewer-test.js, src/lib/viewers/media/__tests__/MediaBaseViewer-test.js, src/lib/viewers/text/CSVViewer.js, src/lib/viewers/text/PlainTextViewer.js, src/lib/viewers/text/__tests__/PlainTextViewer-test.js
Tests on the way, adding checks for media and text viewers.
=> Chore: Adding download reachability checks to other viewers

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v0.16.0
=> Update: box-annotations to v0.16.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.1.0
=> Update: box-annotations to v1.1.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.1.1
=> Update: box-annotations to v1.1.1

.github/ISSUE_TEMPLATE.md
If we like the language here I can add this to our other repos.
=> Docs: Updating issue template

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.2.0
=> Update: box-annotations to v1.2.0

functional-tests/constants.js, functional-tests/fileOptions_test.js, functional-tests/media-controls.html, functional-tests/media_controls_test.js, src/lib/viewers/media/DashViewer.js, src/lib/viewers/media/__tests__/DashViewer-test.js
Fixes the bug where media files showed no duration when previewed.
=> Fix: Revert media duration setting to on loadeddata

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v/1.3.0
=> Update: box-annotations to v1.3.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.3.1
=> Update: box-annotations to v1.3.1

src/lib/polyfill.js
This reverts commit 95def3b94705589a01730d9fbb7a348029fc9b10.
=> Revert "Fix: Add blend mode fallbacks if not supported (#758)"

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.4.0
=> Update: box-annotations to v1.4.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.5.0
=> Update: box-annotations to v1.5.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v1.6.0
=> Update: box-annotations to v1.6.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v2.0.0
=> Update: box-annotations to v2.0.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v2.0.1
=> Update: box-annotations to v2.0.1

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v2.1.0
=> Update: box-annotations to v2.1.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v2.2.0
=> Update: box-annotations to v2.2.0

README.md
=> Add docs for token generator function

src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
Stub out actually opening content inside an iframe.
=> Fix: Flaky ImageViewer test

build/RsyncPlugin.js
=> Build: Hide rsync file list

CHANGELOG.md, README.md, package.json
This reverts commit 2953369d3eeab32b461ae433909384fb927582e8.
=> Revert "Release: 1.47.0"

CHANGELOG.md, README.md, package.json
This reverts commit 47cf6f456fccb962a23122053e620669e7569928.
=> Revert "Release: 1.49.0"

README.md, src/lib/Preview.js, src/lib/__tests__/Preview-test.js, src/lib/viewers/media/DashViewer.js, src/lib/viewers/media/MediaBaseViewer.js, src/lib/viewers/media/__tests__/DashViewer-test.js, src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
=> Update: Preview should allow disabling of  auto focus

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v2.3.0
=> Update: box-annotations to v2.3.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v3.1.0
=> Update: box-annotations to v3.1.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/v3.2.0
=> Update: box-annotations to v3.2.0

package.json, yarn.lock
This reverts commit 18b78322e12e103d29f0963be44403ee5f250cfd.
=> Fix: Downgrade annotations to 2.3.0

package.json, yarn.lock
https://github.com/box/box-annotations/releases/tag/3.3.0
=> Update: box-annotations to 3.3.0

UPGRADING.md, src/lib/Preview.js, src/lib/__tests__/Preview-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
=> New: Expose thumbnails sidebar as preview option

src/lib/icons/thumbnails-toggle-icon.svg
=> Update: Use correct toggle sidebar icon

src/lib/ThumbnailsSidebar.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/_docBase.scss
=> Update: Thumbnails navigation

src/lib/events.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
=> Update: Emit metrics for Thumbnail Sidebar usage

src/lib/viewers/doc/_docBase.scss
=> Chore: Change thumbnail selection to be #444

src/lib/ThumbnailsSidebar.js, src/lib/__tests__/ThumbnailsSidebar-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/_docBase.scss, test/integration/document/Thumbnails.e2e.test.js
=> Fix: Keyboard shortcuts for thumbnails sidebar

src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/DocPreloader.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js, src/lib/viewers/doc/__tests__/DocPreloader-test.js, src/lib/viewers/doc/_docBase.scss
=> Fix: Fix resize logic during preload and opening of thumbnails

package.json, yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2019-10742
=> Update: Upgrade axios to address security vulnerability

src/lib/MetadataAPI.js, src/lib/__tests__/metadataAPI-test.js, src/lib/metadataAPI.js
=> New: metadataAPI.js

src/lib/icons/file_autocad.svg, src/lib/icons/icons.js
=> New: Autocad svg

src/lib/icons/icons.js, src/lib/viewers/office/OfficeLoader.js, src/lib/viewers/office/README.md, src/lib/viewers/office/__tests__/OfficeLoader-test.js
Extending the preview with Excel Online functionality to xlsm and xlsb file formats
=> New(preview): Adding preview with excel online for xlsb & xlsm files

src/lib/viewers/text/BoxCSV.js
=> fix(csv): Avoid mutation in CSV viewer when sorting for column count

src/lib/viewers/doc/DocFindBar.scss
=> style(doc-find-bar): Misaligned in Chrome

build/release.sh
Adding dry_run option to release script for easier testing.
=> chore(build): Add dry run option

package.json, yarn.lock
[Cypress Changelog](https://docs.cypress.io/guides/references/changelog.html)
=> chore(deps): Upgrade cypress to latest available version

build/release.sh
* Check to ensure a back up of readme exists before deleting it.
=> fix(build): guard for removing readme file

src/lib/Preview.js, src/lib/__tests__/Preview-test.js, test/integration/document/Thumbnails.e2e.test.js
* Adds helper method to check if printing is available on the preview instance
=> feat(print): add check to see if printing is available

CONTRIBUTING.md
=> docs(license): Update license link to Box CLA

src/lib/viewers/BaseViewer.js, src/lib/viewers/__tests__/BaseViewer-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
Requires https://github.com/box/box-annotations/pull/508 to function properly.
Todo
=> feat(annotations): Add support for image annotations

src/lib/AnnotationControls.ts, src/lib/__tests__/AnnotationControls-test.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/__tests__/BaseViewer-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
=> feat(annotations): Press Esc to exit annotations mode

src/lib/AnnotationControls.scss
Tested in Chrome, Firefox, Safari, Edge (legacy), and IE11.
=> fix(controls): Fix background color position for region toggle button

src/lib/viewers/doc/_docBase.scss
=> feat(annotations): Hide PopupCursor in discovery default mode

src/lib/viewers/BaseViewer.js, src/lib/viewers/__tests__/BaseViewer-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/__tests__/DocBaseViewer-test.js, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
=> fix(annotations): move discoverability changes into DocBaseViewer

src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
=> fix(discoverability): add getInitialAnnotationMode override

src/lib/viewers/image/ImageBaseViewer.js, src/lib/viewers/image/ImageControls.tsx, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/MultiImageControls.tsx, src/lib/viewers/image/MultiImageViewer.js, src/lib/viewers/image/__tests__/ImageBaseViewer-test.js, src/lib/viewers/image/__tests__/ImageControls-test.jsx, src/lib/viewers/image/__tests__/ImageViewer-test.js, src/lib/viewers/image/__tests__/MultiImageControls-test.jsx, src/lib/viewers/image/__tests__/MultiImageViewer-test.js
=> feat(controls): Create react core controls for image viewers

test/support/constants.js
=> test(cypress): Change access token for annotations access

test/support/constants.js
=> test(cypress): Change to new primary token

src/i18n/en-US.properties, src/lib/viewers/doc/DocFindBar.js
fix(DocFindBar): Add aria-label to docfindbar input field
=> fix(DocFindBar): Add aria-label to docfindbar input field

src/i18n/en-US.properties, src/lib/PreviewUI.js, src/lib/shell.html
- Missing alt attribute doesn't compliant a11y standards.
=> fix(a11y): Add meaningful alt text to custom logo

src/lib/viewers/box3d/Box3D.scss, src/lib/viewers/box3d/Box3DViewer.js, src/lib/viewers/box3d/model3d/Model3DControlsNew.tsx, src/lib/viewers/box3d/model3d/Model3DViewer.js, src/lib/viewers/box3d/model3d/__tests__/Model3DControlsNew-test.tsx, src/lib/viewers/box3d/model3d/__tests__/Model3DViewer-test.js, src/lib/viewers/controls/icons/IconVr24.tsx, src/lib/viewers/controls/model3d/VrToggleControl.scss, src/lib/viewers/controls/model3d/VrToggleControl.tsx, src/lib/viewers/controls/model3d/__tests__/VrToggleControl-test.tsx
=> feat(controls): Add VR button to Model3D controls

package.json, yarn.lock
Updates box-ui-elements to latest version where we will have access to experiences passed down through props
=> chore(deps): Upgarde box-ui-elements to latest available version

src/lib/viewers/box3d/Box3DViewer.js, src/lib/viewers/box3d/__tests__/Box3DViewer-test.js, src/lib/viewers/box3d/image360/Image360Controls.tsx, src/lib/viewers/box3d/image360/Image360Viewer.js, src/lib/viewers/box3d/image360/__tests__/Image360Controls-test.tsx, src/lib/viewers/box3d/image360/__tests__/Image360Viewer-test.js
=> feat(controls): Add React controls for Image360

src/i18n/en-US.properties, src/lib/shell.html, src/lib/viewers/BaseViewer.js, src/lib/viewers/doc/DocBaseViewer.js
Adds a couple aria-label attributes for screen-reader users
=> fix(ThumbnailSidebar): A11Y add descriptive attributes

src/lib/viewers/iframe/IFrameLoader.js, src/lib/viewers/iframe/IFrameViewer.js, src/lib/viewers/iframe/README.md, src/lib/viewers/iframe/__tests__/IFrameLoader-test.js, src/lib/viewers/iframe/__tests__/IFrameViewer-test.js
Removes traces of boxdicom support from the readme, iframeviewer and iframeloader.
=> feat(viewer): Fully remove boxdicom support

package.json, src/lib/viewers/doc/_docBase.scss, yarn.lock
moved media query definitions to Preview.
=> feat(annotations): responsive media queries for annotations-only ctrls

.nvmrc, .travis.yml, package.json, src/lib/viewers/controls/media/TimeControls.tsx, src/lib/viewers/controls/media/__tests__/TimeControls-test.tsx, yarn.lock
This reverts commit 05f31b86f179580e44074a5d0af34dcec0b643cd.
=> Revert "feat(node-18-upgrade): Node 18 Upgrade (#1491)"

src/i18n/en-US.properties, src/lib/RepStatus.js, src/lib/__tests__/RepStatus-test.js, src/lib/events.js
Support new messages for conversion error codes
=> feat(error-codes): Add additional conversion error codes

README.md
Update out of date link to supported file types
=> chore(readme): Update link to supported filetypes

src/i18n/en-US.properties, src/lib/__tests__/PreviewError-test.js, src/lib/viewers/archive/ArchiveViewer.js, test/integration/sanity/Download.e2e.test.js
Update preview error messages to let users know they can download/open the file to view it.
=> feat(error-messages): Update error messages in preview

src/lib/VirtualScroller.js
- Make logic clearer when deleting items out of view elements
- Update comments
=> fix(virtualscroller): accurately remove scrolled-out elements

src/lib/constants.js, src/lib/viewers/doc/DocFirstPreloader.js, src/lib/viewers/doc/Document.scss, src/lib/viewers/doc/Presentation.scss, src/lib/viewers/doc/__tests__/DocFirstPreloader-test.js, src/lib/viewers/doc/_docBase.scss
Removing the loading spinner from the doc first preloader
=> feat(doc-first): removing spinner

src/lib/Preview.js, src/lib/__tests__/Preview-test.js, src/lib/viewers/doc/DocBaseViewer.js, src/lib/viewers/doc/DocFirstPreloader.js
- added a function that can be called externally e.g. from EUA to load viewer assets instead of just prefetching them
- updated unit tests
- Added the new exif reader to the existing asset prefetching logic.
=> feat(pdfjs-preloading): add function to preload pdfjs assets

package.json, src/lib/constants.js, src/lib/viewers/BaseViewer.js, src/lib/viewers/image/Image.scss, src/lib/viewers/image/ImageViewer.js, src/lib/viewers/image/__tests__/ImageViewer-test.js
This PR enhances the ImageViewer's loading performance and reliability by optimizing image completion detection and improving the prefetch functionality. The changes reduce loading times for already-cached images and make the prefetch system more robust with better error handling and comprehensive test coverage.
- **Immediate Loading Detection**: Added logic to `handleAssetAndRepLoad()` to immediately call `finishLoading()` if an image is already complete (cached), eliminating unnecessary wait times
- **Enhanced Prefetch System**: Extended the `prefetch()` method to support a new `preload` option alongside the existing `content` option for more flexible prefetching strategies
- **Browser Memory Caching**: Prefetched images are now rendered in the DOM (hidden off-screen) which forces the …
=> feat(imageviewer): optimizations to prefetch
