box/box-content-preview

- src/lib/viewers/box3d/video360/Video360.scss
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaControls.js
- src/lib/viewers/media/MediaControls.scss
- src/lib/viewers/media/VideoBaseViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
- src/lib/viewers/media/__tests__/MediaControls-test.js
- src/lib/viewers/media/__tests__/VideoBaseViewer-test.js
- Scrubber responds to touch events
- Controls are toggled on touch
- Controls are not always force show due to video360 css
> Fix: Media controls and usability fixes for mobile

- src/lib/PreviewUI.js
- src/lib/__tests__/PreviewUI-test.js
- src/lib/viewers/media/VideoBaseViewer.js
- src/lib/viewers/media/__tests__/VideoBaseViewer-test.js
Additional fixes:
- Hides the play button when 'waiting' after a seek
- Hides the loading icon if you pause while the video is buffering
> Fix: Restore crawler for buffering video

- src/lib/Controls.scss
- Adding it to `.bp-controls-cell` for when the button is disabled
- `user-select: none` prevents copy paste dialog from appearing on control bar
> Fix: Prevent double tap zoom in control bar

- src/lib/Browser.js
- src/lib/__tests__/Browser-test.js
Apple fixed the font issue in 10.3.2, so we only limit the disableFontFace fix to 10.3.1
> Fix: Limit iOS font fix to 10.3.1

- src/lib/viewers/media/MP3.scss
Caused by switching to using both opacity and visibility to hide/show the controls. The reason for that change was so that the controls were not clickable while hidden and could still use the fade in/out transition.
> Fix: Prevent MP3 from hiding

- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
This was blocking annotation creation on mobile.
> Fix: Don't swallow 'touchstart' event to prevent iOS inertia scrolling

- src/lib/_common.scss
So that by default it doesn't render all squishy making the user consider it to be a bug. Some dimensions will at least show some preview.
> Fix: Give preview some min width and height

- src/lib/viewers/doc/_docBase.scss
We should do this first, then we can discuss supplying SVG's to fully support native PDF annotations.
> Fix: Allow legacy annotations to render in PDF.js

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
- click handlers were moved into docBase which meant that the image point annotation button no longer had a handler associated with it
> Fix: Add clickHandlers back for all enabled annotation modes

- src/lib/annotations/AnnotationDialog.js
- src/lib/annotations/annotationConstants.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocHighlightDialog.js
- src/lib/annotations/doc/__tests__/docAnnotatorUtil-test.js
- src/lib/annotations/doc/docAnnotatorUtil.js
- This also prevents highlight dialogs from triggering while the mouse is over a point dialog
> Fix: Don't trigger highlight dialogs while mouse is over another dialog

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Annotator is currently always being loaded with scale 1. When the true scale is set, the annotations are not re-rendered. As a result, annotations on page load will always be the same size.
Proposed changes:
-  annotator.setScale() returns this (annotatorInstance) so that calls can be used in a builder format. ie annotator.setScale().init(), unfortunately prettier formats these calls all on one line. Might be useful to anyone who has forked the repository.
-  Update the viewer scale just before loading the annotations
-  Assign annotatedElement in Annotator constructor rather than init() so that annotatorInstance.setScale(trueScale) can be called before annotator.init(). Init() will render the annotations and require a rescale. As init() appears to be called right after constructing …
> Fix: Load annotator with the correct initial scale

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Thanks to @pramodsum for the catch.
Fancy destructure syntax was no good here.
> Fix: Emit scale does not always pass events

- src/lib/Controls.scss
- src/lib/_common.scss
- src/lib/constants.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- Mobile Safari is the only browser we support that doesn't support the Fullscreen API. This change sets the content to fill the viewport by `setting position: fixed`
- Added touch-action manipulation to prevent double-tap zoom on the content
> New: Add pseudo fullscreen to mobile Safari

- src/lib/viewers/doc/DocBaseViewer.js
- src/third-party/doc/0.130.0/images/annotation-noicon.svg
#257 without a new third-party doc version.
> New: add annotation-noicon to allow native PDF annotations to be shown

- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- Prevents other highlight dialogs from being triggered while a shared dialog for creating highlight annotations is already open
> Fix: Don't trigger highlight if a new highlight is being created

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/image/ImageAnnotator.js
- src/lib/annotations/image/__tests__/ImageAnnotator-test.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
- Use touchstart and mousedown to trigger the creation of point annotations
- Swap out event with touchEvent if the user is on a mobile device
> Chore: Removing references to annotations from individual viewers

- src/lib/PreviewUI.js
- src/lib/__tests__/PreviewUI-test.js
- The notification object was getting initialized in the viewer container on top of the loading indicator which prevented the download button in the loading indicator from triggering anything
> Fix: Only initialize PreviewUI.notification after viewer is loaded

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Do NOT merge before https://github.com/box/box-content-preview/pull/271
> Chore: Cleaning up annotations methods in BaseViewer

- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
Shaka-player changed its behavior when selecting a variant. We now have
to explicitly disable adaptation. See notes below (which also apply to
upgrade from 2.0 to 2.1):
https://github.com/google/shaka-player/blob/master/docs/tutorials/upgrade-v2-0.md
NOTE: From my testing, their example doesn't actually work, and I need
to disable adaptation BEFORE selecting the variant. I filed https://github.com/google/shaka-player/issues/962 on shaka team for this
> Fix: Forcing HD/SD should disable adaptation

- build/release.sh
GitHub releaser script output was interpreted as an error response - we explicitly return 0 with success.
> Fix: Fix release script after GitHub release

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
Bug: open a file with annotations,
click point mode and change the browser window size and the annotations will not redraw.
Cause: unbindDOMModeListeners is being called on entering annotation mode. This method removes the scale listener.
> Fix: scale being unbound when annotating

- src/lib/annotations/Annotator.js
- src/lib/annotations/BoxAnnotations.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/drawing/DrawingThread.js
I previously (unnecessarily) bound pointClickHandler to the wrong object. Also moving DrawingThread handler bindings to the constructor.
> Fix: annotation handler rebinding

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Increase document file size limit for disabling range requests for users with a non-US locale from 5MB to 25MB. This will hopefully improve performance of previews for larger documents outside the US since we are still limited by latency from round trips.
> Update: Increase file size limit for range requests

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
This PR uncovered a minor (possible) issue with highlight annotations right now: 
Remove highlights from BoxAnnotations.js. The client side will filter fetched highlight annotations from being displayed but highlight handlers will still be enabled and available.
> Fix: Do not display disabled annotation types on fetch

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
Remove code that supports access token in the options object - this has been deprecated for some time now.
> Chore: Remove code supporting token in options object

- src/lib/annotations/AnnotationService.js
- The annotations API refers to thread numbers as thread, therefore any create API request MUST provide the threadNumber as thread as to avoid adding the new annotation to it's own thread and incrementing the threadNumber
- Any annotation created since https://github.com/box/box-content-preview/pull/241 in [v1.3.0](https://github.com/box/box-content-preview/releases/tag/v1.3.0) will not have the correct thread number associated with it. Instead each annotation will have a unique thread number. This will be fixed in v1.7.0
> Fix: Create annotation in API using thread rather than threadNumber

- src/lib/annotations/Annotator.scss
- src/lib/annotations/MobileAnnotator.scss
- src/lib/annotations/image/ImagePointThread.js
- src/lib/annotations/image/__tests__/ImagePointThread-test.js
- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- Ensures that dialog.position doesn't get called for image point annotations 
- Added styling to the create annotation text area container so that it fits inside the tablet annotations dialog that slides out from the right 
- Removes 'zoomable' and 'pannable' classes from image when the image viewer controls are disabled
- Added extra padding below reply-container on mobile annotation dialogs so that the post/cancel buttons are displayed properly irrespective of whether or not the container can scroll
> Fix: Point annotation cleanup

- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
@pramodsum 
The data-scale attribute is set to infinity when an Image element has a naturalWidth and naturalHeight of 0. This circumvents the problem even though IE11 is supposed to support naturalWidth and naturalHeight. It might be that naturalWidth and naturalHeight are eventually set but the setting is not done on load. In any case, this seems to fix the issue (tested on IE11).
> Fix: Inconsistent natural image dimensions in IE

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/file-test.js
- src/lib/file.js
- Partially reverts changes from #24 and will enable #326
- Adds 'id' to FILE_FIELDS since we use that to validate the file object passed in
> New: Support well-formed file object in show()

- src/lib/annotations/MobileAnnotator.scss
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocDrawingThread.js
- src/lib/annotations/doc/DocHighlightThread.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/doc/__tests__/docAnnotatorUtil-test.js
- src/lib/annotations/doc/docAnnotatorUtil.js
- Fixes the bug where the annotations canvas fails to re-render on zoom which results in highlights and drawings being incorrectly positioned
- Includes a CSS fix for highlight create dialog on mobile
> Fix: Re-scale annotation canvases on zoom

- src/i18n/en-US.properties
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaControls.js
- src/lib/viewers/media/Settings.js
- src/lib/viewers/media/Settings.scss
- src/lib/viewers/media/__tests__/DashViewer-test.js
- src/lib/viewers/media/__tests__/MediaControls-test.js
- src/lib/viewers/media/__tests__/Settings-test.js
New: Support multiple audio tracks
This commit adds support for selection of different audio tracks when
available in the manifest. It selects based on a combination of the
language and "role" of the audio track. This combination should be
unique in order to unambiguously select audio tracks - roles are made
unique by the backend, as audio0, audio1, etc.
One thing to be careful of in all this is how this interacts with
selecting HD/SD video. Previous implementation would cache the HD/SD
variant to switch to. Now, there are multiple HD variants and multiple
SD variants, because the HD stream could have different audio. Thus this
required some refactoring of how we pick the HD/SD streams, so that we
maintain the same audio stream while changing video quality. In the
process, I've also fixed …
> Multi audio

- src/lib/annotations/AnnotationThread.js
- src/lib/annotations/annotatorUtil.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocHighlightThread.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/doc/__tests__/DocHighlightThread-test.js
- src/lib/annotations/doc/__tests__/docAnnotatorUtil-test.js
- src/lib/annotations/doc/docAnnotatorUtil.js
- This prevents some dialog flickering when moving the mouse from the annotations icon to the dialog
> Chore: Don't hide dialog on mouseout if mouse is in annotations dialog

- src/lib/annotations/AnnotationThread.js
- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocHighlightDialog.js
- src/lib/annotations/doc/DocHighlightThread.js
- src/lib/annotations/doc/DocPointThread.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/doc/__tests__/DocHighlightDialog-test.js
- src/lib/annotations/doc/__tests__/DocHighlightThread-test.js
- src/lib/annotations/doc/__tests__/DocPointThread-test.js
- src/lib/annotations/image/ImageAnnotator.js
- src/lib/annotations/image/ImagePointThread.js
- src/lib/annotations/image/__tests__/ImagePointThread-test.js
- src/lib/viewers/BaseViewer.js
Enables annotations to be shown in a view-only setting with the correct scopes
Annotations permissions will be as follows:
- can_annotate - whether a user can add any new annotations
- can_view_annotations_all - whether a user can view all annotations
- can_view_annotations_self - whether a user can view their own annotations (The API should return only the current user's annotations for this scope)
> New: Separate create and view permissions for annotations

- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/Annotator-test.js
- Annotation mode exits using the wrong button element. This causes the wrong one to become in-active
- When calling fetchannotations() without permissions to view all or own annotations, a non-promise unexpectedly returned.
> Fix: annotation mode exits on wrong button and fetch annotations returns non-promise

- src/lib/annotations/Annotator.js
- src/lib/annotations/doc/DocAnnotator.js
- Object.values() is not supported in any IE browser
> Fix: Swapping Object.values() with Object.keys()

- src/lib/annotations/Annotator.js
- src/lib/annotations/BoxAnnotations.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/__tests__/BoxAnnotations-test.js
- src/lib/annotations/__tests__/annotatorUtil-test.js
- src/lib/annotations/annotationConstants.js
- src/lib/annotations/annotatorUtil.js
- src/lib/constants.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Annotations should be rendered in view-only if at LEAST one of the correct annotation permissions are true. This fully completes the separation of create + view permissions from #358.
> Fix: Respect view permissions when viewer.initAnnotations() is called

- src/i18n/en-US.properties
- src/lib/Preview.js
- src/lib/RepStatus.js
- src/lib/__tests__/RepStatus-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/box3d/model3d/Model3DRenderer.js
> New: More specific error messages from conversion

- src/lib/annotations/AnnotationModeController.js
- src/lib/annotations/AnnotationThread.js
- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/AnnotationModeController-test.js
- src/lib/annotations/__tests__/AnnotationThread-test.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/annotationConstants.js
- src/lib/annotations/doc/CreateHighlightDialog.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocDrawingThread.js
- src/lib/annotations/doc/__tests__/CreateHighlightDialog-test.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/doc/__tests__/DocDrawingThread-test.js
- src/lib/annotations/drawing/DrawingModeController.js
- src/lib/annotations/drawing/DrawingThread.js
- src/lib/annotations/drawing/__tests__/DrawingModeController-test.js
- src/lib/annotations/drawing/__tests__/DrawingThread-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Emits annotator and annotation thread specific events to the Viewer and Preview
Annotator Events: 
- annotationmodeenter: Enter an annotation mode
- annotationmodeexit: Exit an annotation mode
- annotationsfetched: Annotations have been fetched from the API
- annotationerror: Annotation error occurred
Annotation Thread Events:
- annotationpending: Thread was created but not saved
- annotationthreadsaved: Annotation thread saved on the server
- annotationthreaddeleted: Annotation thread deleted on the server
- annotationsaved: Annotation saved on an existing thread on the server
- annotationdeleted: Annotation deleted from an existing thread on the server
- annotationdeleteerror: Error while deleting an annotation on either an existing/new thread
- annotationcanceled: Annotation cancelled …
> New: Emit annotation thread events to the viewer and beyond

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/tokens-test.js
- src/lib/tokens.js
Allows tokens to be null or undefined. Useful when the passed in file or collection has well formed file objects. This is for offline use case or the use case where the parent project (like ContentExplorer UI Element) has already made the call.
Also changes the token getter to pass in typed ids for files and handle cases when typed ids are returned from the token service to make it consistent with other UI Elements. Since all the UI elements can either be requesting `folder` or `file` ids, the token service needs to know what type of id we are sending it, as such either `file_` or `folder_` is prefixed to all the ids. Likewise the token service can/will return typed ids after fetching tokens. So it needs to be mapped back to what preview wants.
> Update: Allow passed in collections to be of file objects

- src/lib/annotations/Annotator.scss
> Fix: Show point annotation above dialog only on hover

- src/lib/Browser.js
- src/lib/Logger.js
- src/lib/Preview.js
- src/lib/__tests__/Logger-test.js
- src/lib/__tests__/Preview-test.js
This information should only be fetched once rather than each time a Logger is instantiated for every Viewer
> Chore: Only getBrowserInfo() once per preview instance

- build/karma.conf.js
- src/lib/constants.js
New version of pdf.js is showing a lot more console errors and is causing problems with Catchpoint.
> Fix: Downgrade pdf.js

- package.json
- src/lib/Preview.js
- src/lib/__tests__/util-test.js
- src/lib/file.js
- src/lib/util.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/box3d/video360/Video360Viewer.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/MultiImageViewer-test.js
- src/lib/viewers/media/MediaControls.js
- src/lib/viewers/swf/SWFViewer.js
- src/lib/viewers/text/__tests__/CSVViewer-test.js
- yarn.lock
- Replace manual URL manipulation with jsuri library
- Add support for new `queryParams` Preview option. When used, each key/value pair will be appended to all API requests as query params
> Update: Support additional query params in requests

- src/lib/PreviewUI.js
- src/lib/__tests__/PreviewUI-test.js
- src/lib/annotations/AnnotationModeController.js
- src/lib/annotations/Annotator.js
- src/lib/annotations/Annotator.scss
- src/lib/annotations/BoxAnnotations.js
- src/lib/annotations/__tests__/AnnotationModeController-test.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/__tests__/annotatorUtil-test.html
- src/lib/annotations/__tests__/annotatorUtil-test.js
- src/lib/annotations/annotationConstants.js
- src/lib/annotations/annotationsShell.html
- src/lib/annotations/annotatorUtil.js
- src/lib/annotations/drawing/DrawingModeController.js
- src/lib/annotations/drawing/__tests__/DrawingModeController-test.js
- src/lib/constants.js
- src/lib/shell.html
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
> New: Draw annotations UI

- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
In theory, if a content-url-template is given with watermark-cache
(cache-busting) params from the server, all dash requests should carry
those cache-busting params. They did not however, because the
content-url-template is only used to construct the URL of the manifest -
the segment URLs are constructed by shaka-player itself, based on the
manifest url, but ignores all query-params on the manifest. This is why
we have a requestFilter function, but watermark-cache busting parameters
weren't taken into account. This commit adds a watermark cache-busting
parameter to every segment request, if the file is watermarked.
> Fix: Set watermark-cache params for dash segments

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- Checkbox/radio button styling can be incorrect with interactive forms
- Interactive styling is distinct and some customers don't want it
- Forms are pseudo-interactive - changed data isn't actually saved
> Fix: Turn off rendering interactive forms

- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/Settings.js
@bhh1988 was caching of media settings working previously? I observed it being broken on live since the cache object is getting cleared on each navigate/hide.
> Fix: Use local storage to cache media settings

- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
There is a "data" property to the shaka error object, which gives more
useful detail on the error, especially for media-element errors. See
https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html for
the various errors.
> Chore: Add more detail to shaka error logging

- src/lib/annotations/AnnotationDialog.js
- src/lib/annotations/AnnotationService.js
- src/lib/annotations/AnnotationThread.js
- src/lib/annotations/Annotator.js
- src/lib/annotations/CommentBox.js
- src/lib/annotations/__tests__/AnnotationDialog-test.js
- src/lib/annotations/__tests__/Annotator-test.js
- src/lib/annotations/__tests__/CommentBox-test.js
- src/lib/annotations/__tests__/annotatorUtil-test.js
- src/lib/annotations/annotationConstants.js
- src/lib/annotations/annotatorUtil.js
- src/lib/annotations/doc/CreateHighlightDialog.js
- src/lib/annotations/doc/DocAnnotator.js
- src/lib/annotations/doc/DocDrawingDialog.js
- src/lib/annotations/doc/DocDrawingThread.js
- src/lib/annotations/doc/DocHighlightDialog.js
- src/lib/annotations/doc/__tests__/CreateHighlightDialog-test.js
- src/lib/annotations/doc/__tests__/DocAnnotator-test.js
- src/lib/annotations/doc/__tests__/DocDrawingDialog-test.js
- src/lib/annotations/doc/__tests__/DocHighlightDialog-test.js
- src/lib/annotations/doc/__tests__/DocHighlightThread-test.html
- src/lib/annotations/doc/__tests__/DocHighlightThread-test.js
- src/lib/annotations/doc/__tests__/DocPointDialog-test.js
- src/lib/annotations/drawing/DrawingThread.js
- src/lib/annotations/image/ImageAnnotator.js
- src/lib/annotations/image/__tests__/ImageAnnotator-test.js
- src/lib/annotations/image/__tests__/ImagePointDialog-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Since BoxAnnotations will be included as an npm package, it will not be able to use the mojito generated versions of the code based on the locale. Until BoxAnnotations can be written in React with it's own localization strategy, a temporary solution will be to pass in the localized strings as an option from Preview into BoxAnnotations on initialization. 
- Tests + documentation coming soon
> Chore: Passing localized strings into annotations

- src/lib/viewers/box3d/video360/Video360Loader.js
- src/lib/viewers/box3d/video360/__tests__/Video360Loader-test.js
With Safari 11, the long-standing "DOM Exception" bug with video tags and WebGL has been fixed.
> New: Enable 360 video on desktop Safari

- src/lib/annotations/BoxAnnotations.js
- src/lib/annotations/README.md
- src/lib/annotations/__tests__/BoxAnnotations-test.js
Adding `enabledTypes` to the annotation configuration, as well as a default enabled annotation types(`DEFAULT_ENABLED`), if none provided, to `ANNOTATORS`. This allows us to specify all of the *allowed* kinds of annotators, and the ones that are enabled by default (if no config provided).
IE)
```
// for document annotator, results in only 'point' annotations, as timestamp are not allowed
enabledTypes: ['point', 'timestamp']
```
> New: Added enabledTypes property. Backwards compat for disabledTypes

- src/lib/annotations/AnnotationModeController.js
- src/lib/annotations/Annotator.js
- src/lib/annotations/__tests__/AnnotationModeController-test.js
Temporary fix until mode specific logic is moved into annotation controllers
> Fix: controller.handleAnnotationEvent() not bound correctly

- src/lib/constants.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Explicitly check for success status instead of checking against error since we also can't show a pending image rep
> Fix: Instant Preview when thumbnail is pending

- package.json
- yarn.lock
* Chore: Cleaning up mobile phone drawing CSS (#17) ([b125b8b](https://github.com/box/box-annotations/commit/b125b8b))
* Chore: Move controllers into a separate folder (#18) ([3efa19f](https://github.com/box/box-annotations/commit/3efa19f))
* Chore: Paging draw threads in the controller's internal thread map (#6) ([fc52e9e](https://github.com/box/box-annotations/commit/fc52e9e))
* Chore: Refactoring annotation mode logic into controllers (#15) ([2be6ba3](https://github.com/box/box-annotations/commit/2be6ba3))
* Chore: Separate fetching and rendering of annotations (#16) ([328681e](https://github.com/box/box-annotations/commit/328681e))
*  Chore: Store threads.annotations as an object by annotationID (#5) …
> Update: box-annotations to v0.2.0

- package.json
- yarn.lock
* Chore: Add conventional-changelog-releaser (#34) ([624e0bd](https://github.com/box/box-annotations/commit/624e0bd))
* Chore: Do not clear out node_modules on when publishing npm package (#30) ([08c180d](https://github.com/box/box-annotations/commit/08c180d))
* Fix: Do not select drawings when creating a point annotation on top (#28) ([07fc4c1](https://github.com/box/box-annotations/commit/07fc4c1))
* Fix: Drawing CSS (#23) ([0493fcd](https://github.com/box/box-annotations/commit/0493fcd))
* Fix: fix highlight selection and typos (#21) ([ca54d5e](https://github.com/box/box-annotations/commit/ca54d5e)), closes [#21](https://github.com/box/box-annotations/issues/21)
* Fix: Hide createHighlightDialog on page re-render (#31) …
> Update: box-annotations to v0.3.0

- src/lib/viewers/office/OfficeViewer.js
- src/lib/viewers/office/__tests__/OfficeViewer-test.js
Original fix here: https://github.com/box/box-content-preview/pull/444
feeling the pain of repeated code
> Fix: Correctly revoke objectURL for print blob in office viewer

- package.json
- yarn.lock
* Release: 0.3.1 ([6af2062](https://github.com/box/box-annotations/commit/6af2062))
* Fix: Disable highlight creation when the mobile shared dialog is visible (#35) ([de7f392](https://github.com/box/box-annotations/commit/de7f392))
* Fix: Ensure commentbox event listeners are bound properly (#37) ([fcce638](https://github.com/box/box-annotations/commit/fcce638))
*  Fix: Ensure newly created threads are set as inactive while saving (#38) ([8072fa8](https://github.com/box/box-annotations/commit/8072fa8))
> Update: box-annotations to v0.3.1

- src/lib/constants.js
- src/lib/viewers/doc/DocPreloader.js
- src/lib/viewers/doc/PresentationPreloader.js
- src/lib/viewers/doc/__tests__/DocPreloader-test.js
This now matches the behavior of the presentation viewer, which doesn't have a max zoom scale.
> Fix: Presentation preloading scales without max

- src/lib/__tests__/file-test.js
- src/lib/file.js
Append file version to streaming download endpoint so a preview of a different file version doesn't render a cached file.
> Fix: Cachebust original representation URL

- src/lib/viewers/media/Settings.js
- src/lib/viewers/media/Settings.scss
- src/lib/viewers/media/__tests__/Settings-test.js
Add class to hide overflow during menu transitions and hide after transitions.
> Fix: Media player control menus show scrollbars during transition

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
Solves:
```
There is one issue in preview right now...if you call preview.show(...,...,options)...and then after call preview.show() again with different options, the 2nd time the options are not parsed and ignored
cuz of https://github.com/box/box-content-preview/blob/master/src/lib/Preview.js#L599
returns after loadFromServer()
probably the retryCount should be reset to 0 when stuff has loaded successfully
```
> Fix: Reset retry count after successful preview

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Context was bound to the fetch resize handler function instead of the actual handler
> Fix: BaseViewer debounced resize handler binding

- package.json
- yarn.lock
* Chore: Cleanup annotations permissions (#40) ([a52ed54](https://github.com/box/box-annotations/commit/a52ed54))
* Fix: Activate annotation dialog on post (#42) ([bc001be](https://github.com/box/box-annotations/commit/bc001be))
* Fix: Disable highlight creation when the mobile shared dialog is visible (#35) ([de7f392](https://github.com/box/box-annotations/commit/de7f392))
* Fix: Don't clear reply textarea when annotation is added to dialog (#36) ([1f88d55](https://github.com/box/box-annotations/commit/1f88d55))
* Fix: Ensure commentbox event listeners are bound properly (#37) ([fcce638](https://github.com/box/box-annotations/commit/fcce638))
* Fix: Prevent creation of highlights when a point annotation is pending (#41) …
> Update: box-annotations to v0.4.0

- package.json
- yarn.lock
* Chore: Disable dialog actions until annotation is saved on the server (#48) ([6dbcda2](https://github.com/box/box-annotations/commit/6dbcda2))
* Chore: Remove autobind from base classes (#44) ([639f8d2](https://github.com/box/box-annotations/commit/639f8d2))
* Chore: Remove autobind from doc classes (#46) ([d7ded88](https://github.com/box/box-annotations/commit/d7ded88))
* Chore: Remove autobind from Image classes (#45) ([1dda3a4](https://github.com/box/box-annotations/commit/1dda3a4))
* Chore: Remove NPM install from release/publish scripts (#50) ([48822c4](https://github.com/box/box-annotations/commit/48822c4))
* Update: Remaining packages (#49) ([4dab273](https://github.com/box/box-annotations/commit/4dab273))
*  Update: Sinon to v4.1.2 …
> Update: box-annotations to v0.5.0

- build/webpack.config.js
Options can be found here: https://webpack.js.org/configuration/devtool/
> Chore: Change webpack source maps to 'inline-cheap-source-map'

- build/webpack.karma.config.js
Source maps don't work in phantom, so we should turn them off unless running our tests in debug mode in a browser. This should shave off between 30-45 seconds every place we run our tests; locally, jenkins, and travis.
> Chore: only use source maps when running unit tests in debug mode

- src/lib/Preview.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
This change combined with https://github.com/box/box-annotations/pull/68 will allow a developer to instantiate annotations outside of Preview like this: 
```
const options = {
Image: {
enabledTypes: ['point']
},
// Document/Presentation Annotators are the same so the config is simplified here
Document: {
enabledTypes: ['highlight', 'draw']
}
};
/* global BoxAnnotations */
const boxAnnotations = new BoxAnnotations(options);
var preview = new Box.Preview();
preview.show(FILE_ID, ACCESS_TOKEN, {
container: '.preview-container',
showDownload: true,
boxAnnotations
});
```
> New: Allow BoxAnnotations to be passed in as a Preview option

- src/lib/Preview.js
- src/lib/PreviewUI.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/file-test.js
- src/lib/file.js
- src/lib/viewers/BaseViewer.js
- Never cache watermarked files
- Separate loading and re-loading (when cache is stale or file is newly watermarked) when loading from server
- Remove superfluous caching before loading from cache
- Add new public method to reload current preview and replace legacy methods of reloading preview with new method
> Fix: Never cache watermarked files, add reload() method

- build/upgrade_annotations.sh
Uses a link to the latest release (i.e. https://github.com/box/box-annotations/releases/tag/v0.7.3) instead of https://github.com/box/box-annotations/releases/
> Update: Link to specific Annotations release tag in commit

- src/lib/Preview.js
- src/lib/PreviewUI.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/PreviewUI-test.js
> Fix: Set up notification in Preview.finishLoading()

- src/lib/__tests__/util-test.js
- src/lib/util.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
- src/lib/viewers/doc/_docBase.scss
Still a WIP, but this PR adds a more fluid pinch-to-zoom by:
1. Scaling the visible pages canvases with CSS transform
2. Calculating the overall scale and translate it to a PDF.js zoom
3. Removing the CSS scale and scrolling to where we left off while pinching
Open Issues:
1. Slight jump when transitioning from CSS scaling to PDF.js zoom
2. Pages will occasionally scroll when pinching using the presentation viewer.
> New: Enhanced pinch to zoom

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
When fetching for file info, respect 'Retry-After' header if present. Otherwise, retry with exponential back-off.
> Update: Respect 'Retry-After' header if present

- package.json
- src/lib/Fullscreen.js
- src/lib/__tests__/Fullscreen-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/media/Dash.scss
- yarn.lock
When IE11 was fullscreened it cut off the bottom controls. This was due to a class that gets added when the header is present. The class is supposed to be removed in fullscreen and preview should be shifted up, so the controls won't be cut off.
The issue occured because there was multiple event listeners which got added in the constructor of Fullscreen.js due to the fullscreen API sometimes requiring vendor prefixes [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). This caused the toggle function to be called an even number of times, thus removing and re-adding the header class.
Following the suggestion from MDN, I added fscreen to resolve the cross browser differences and only add 1 event listener instead of 4.
> Fix: fullscreen controls not shown in IE11

- src/lib/_loading.scss
- The preview CSS selector only prevented the div directly adjacent to the .bp-loading-wrapper from being interactable.
- This selector prevents all divs within the Preview Container EXCEPT .bp-loading-wrapper from being interactable. This prevents interactions from the Preview content, find bar, controls, etc.
> Fix: Ensure only loading wrapper is interactable preview container

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/events.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/box3d/Box3DViewer.js
- src/lib/viewers/box3d/__tests__/Box3DViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/error/PreviewErrorViewer.js
- src/lib/viewers/error/__tests__/PreviewErrorViewer-test.js
- src/lib/viewers/iframe/IFrameViewer.js
- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
- src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
- src/lib/viewers/office/OfficeViewer.js
- src/lib/viewers/swf/SWFViewer.js
- src/lib/viewers/text/CSVViewer.js
- src/lib/viewers/text/MarkdownViewer.js
- src/lib/viewers/text/PlainTextViewer.js
- src/lib/viewers/text/__tests__/CSVViewer-test.js
- src/lib/viewers/text/__tests__/MarkdownViewer-test.js
- src/lib/viewers/text/__tests__/PlainTextViewer-test.js
This pull request moves all viewer events into `events.js` to provide documentation for each event and reduce possibility of using the wrong event names.
> Event names into separate file

- src/i18n/en-US.properties
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/constants.js
- src/lib/util.js
- src/lib/viewers/box3d/model3d/Model3DRenderer.js
- src/lib/viewers/error/PreviewErrorViewer.js
- src/lib/viewers/error/__tests__/PreviewErrorViewer-test.js
New Errors:
1. Generic: Only used when we  have no other message to display
2. Unsupported: We can now be sure that the file mentioned is not supported!
3. Account: In the case that Box supports the file, but your tariff does not allow preview for the given type.
> New: Specific error messages for unsupported/tariff restricted files

- src/lib/viewers/media/Settings.js
- src/lib/viewers/media/__tests__/Settings-test.js
Fixes scroll bar cutting off menu
> Fix settings menu title cut off by scrollbar

- src/lib/viewers/box3d/model3d/Model3DControls.js
Looks like we missed removing the unbinding of an event listener to a function that no longer exists
> COXP-4005: Preview JS error in console - 'unable to get property handleEvent' of undefined or null reference

- src/lib/Notification.js
- src/lib/__tests__/Notification-test.js
- src/lib/_common.scss
Also overriding some styles such that the notification is absolute to the top of it's container, rather than fixed to the top of the page.
> Chore: Allow notifications to persist

- src/lib/viewers/doc/DocFindBar.js
Open doesn't need to be bound as it's not used as a handler callback.
> Fix: Bind close method in DocFindBar

- src/lib/_common.scss
The extra padding which accounts for the header is no longer needed since the notification wrapper is positioned absolutely.
> Fix: No longer account for header above notification wrapper

- README.md
- package.json
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/file-test.js
- src/lib/constants.js
- src/lib/file.js
This patch adds support for previewing non-current file versions. Specify the file version like so:
```
const preview = new Box.Preview();
preview.show(FILE_ID_1, ACCESS_TOKEN, {
fileOptions: {
[FILE_ID_1]: {
fileVersionId: FILE_VERSION_ID_1
}
}
});
```
In this patch, we start caching file objects by both file ID and by file version ID, distinguishing between the two with a 'file_' or 'file_version_' prefix as the key to the cache. This allows us to be backwards-compatible and show the current file version if no file version ID is passed in, while always allowing a cached entry of a current version to be overriden when you preview a non-current file version. We abstract this logic to file.js, and rely on the helper methods cacheFile(), uncacheFile(), and getCachedFile() to interact with …
> New: Support previews of non-current file versions

- README.md
- src/lib/Preview.js
- src/lib/util.js
Add new Preview option `disableEventLog` to disable the client-side `preview` log to the Events API. Previews with this option enabled will not increment access stats, but all content access is still logged server-side for audit purposes.
Resolves #471.
> New: Option to disable `preview` event log

- .travis.yml
I've added the env variables to our travis account, so only our internal team can see them. This will mean that for now we cannot run sauce-labs on PRs, as our forks (or external contributor's forks) do not have access to these variables. 
Info on the deprecation here: https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated
> Chore: Removing soon to be deprecated JWT addon in travis

- src/i18n/en-US.properties
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/util-test.js
- src/lib/constants.js
- src/lib/util.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/MultiImageViewer.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
- src/lib/viewers/image/__tests__/MultiImageViewer-test.js
This also will add the check to any generic download request, such as prefetching or preloading. 
Tests on the way, other viewers will be in a separate PR.
> Chore: Add download reachability checks to Document and Image viewers

- README.md
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/util-test.js
- src/lib/util.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/doc/docAssets.js
- src/lib/viewers/text/__tests__/PlainTextViewer-test.js
Rename `pauseRequireJS` option since it's not immediately clear what you'd use it for. We retain support for the older name for backwards compatibility. Also remove unnecessary patching of `require` and `requireJS`.
> Update: Rename 'pauseRequireJS' option to 'fixDependencies'

- src/lib/__tests__/util-test.js
- src/lib/util.js
- src/lib/viewers/doc/docAssets.js
Global define check was causing errors, adding a window.define check and also fixing document viewer to correctly rely on minified pdf.js.
> Fix: define check

- CHANGELOG.md
- README.md
I made a minor release instead of a patch release last week. Upon removing the release, I forgot to update documentation. Fixed to reflect actual patch release
> Chore: update readme and changlog to reflect correct versions

- src/i18n/en-US.properties
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/file-test.js
- src/lib/__tests__/logUtils-test.js
- src/lib/events.js
- src/lib/file.js
- src/lib/logUtils.js
- src/lib/viewers/error/PreviewError.scss
- src/lib/viewers/error/PreviewErrorViewer.js
- src/lib/viewers/error/__tests__/PreviewErrorViewer-test.js
Add error message for un-downloadable file and support for a link button instead of a download button in the error viewer.
> Update: Add un-downloadable error case

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
Retry a maximum of 3 times and use full jitter instead of exponential backoff.
> Update: Modify file info retry logic

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/media/MediaBaseViewer.js
Changed to setup due to prefetch. Refactored tests and getStart* to avoid changing a bunch of test setup
> Fix: move startAt from constructor to setup

- src/lib/__tests__/Preview-test.js
Prettier formatted this file quite a lot,  The actual changes are separating out the current ```prefetchViewers``` tests into a nested describe (line 583), and a new test which has an unstubbed ```getViewers``` (line 629).
This test fails before #690 and now passes
> Chore: add unit test for prefetching actual viewers

- src/lib/polyfill.js
Extending Error to PreviewError requires `babel-plugin-transform-builtin-extend`, which requires Reflect.construct and Array.from. This patch polyfills Reflect.construct, deriving from the core-js polyfill, and Array.from, using the MDN-suggested polyfill.
> Fix: Polyfill Reflect.construct and Array.from for IE11

- README.md
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/util-test.js
- src/lib/util.js
Adds support for passing fileId's as a number. It currently breaks if a number is passed instead of a string
> Chore: support for numeric file id

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
Uppercase the extensions for unsupported file types to prevent the dual period `...didn't load. .zip files...` --> `...didn't load. ZIP files...`
> Update: Uppercase unsupported file types

- src/lib/viewers/media/MediaBaseViewer.js
Number.isFinite() is not supported in IE, and all it does is check that the input is a number and call the global isFinite, which is supported everywhere. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite
> Fix: Avoid use of Number.isFinite()

- package.json
- src/lib/Location.js
- src/lib/__tests__/file-test.js
- src/lib/__tests__/util-test.js
- src/lib/util.js
- src/lib/viewers/office/OfficeViewer.js
- src/lib/viewers/office/__tests__/OfficeViewer-test.js
- yarn.lock
- Move hostname check to Browser function so we can test `isBoxWebApp()`
- Fix incorrect `file.canDownload()` tests, they were missing brackets
- Add missing peer dependency
- Clean up package.json and run `yarn upgrade`
> Chore: Add util tests and fix file tests

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Fixes an issue where document preload was being shown when startAt was set
> Fix: startAt should disable document preload

- src/lib/viewers/doc/_docBase.scss
Old CSS was prevent user selection of anything that wasn't a text layer div to prevent weird selection edge cases. This patch relaxes that to allow selection of `<span>`, `<p>` & `<input>` so annotation dialog text can be selected (they use `<p>`).
> Fix: Allow annotation text to be selectable

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
My misreading lead to a null event_name being used for the metric. This fixes it to use the correct one.
> Use correct property for handle viewer event

- src/lib/Browser.js
- src/lib/__tests__/Browser-test.js
We don't use metrics associated with whether the user's browser supports WebGL or 3D rendering, so this removes the WebGL checks from the browser info check for every Preview instance and isolates them to 3D and 360 files, which should reduce instances of the `Rats! WebGL hit a snag.` error.
> Fix: Reduce WebGL checks to reduce instances of Rats! error

- README.md
- build/karma.conf.js
- build/webpack.config.js
- package.json
- yarn.lock
With Node v8+ we no longer need babel-polyfill for Webpack.
> Chore: Remove unused babel-polyfill

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- Send content disposition header to force representation to be downloaded as attachment
- Expose asset path as method on viewer instead of directly accessing
> Fix: Download watermarked

- build/release.sh
This will prevent patch releases from resetting to upstream/master. Instead, it will reset to the previous version of Preview (if available).
TODO: replicate the same logic in BoxAnnotations
Copy of https://github.com/box/box-content-preview/pull/745
> Chore: Only reset to upstream/master for major/minor releases

- src/lib/Cache.js
- src/lib/DownloadReachability.js
- src/lib/__tests__/Cache-test.js
- src/lib/__tests__/DownloadReachability-test.js
- src/lib/__tests__/util-test.js
- src/lib/util.js
TODO: write tests for when storage is not available
> Fix: Guard session/local storage usage in download reachability

- src/lib/viewers/iframe/IFrameViewer.js
- src/lib/viewers/iframe/__tests__/IFrameViewer-test.js
Use /notes_embedded instead of /notes to resolve X-Frame-Origin issue.
> Fix: Embedded notes in Box WebApp

- src/lib/viewers/media/Settings.scss
Also verified that an item receiving keyboard focus still turns the background blue and the icon white, as before.
> Fix: Correct media settings checkmark icon color on hover

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- Remove incorrect short-circuit-on-retry logic. This short circuit was being called any time you called preview on the same file twice and subsequent loads would always fail because the short circuit happened before an access token was assigned
- Set up fake clock in beforeEach of tests for handleFetchError() - not resetting the timer was causing weird issues
> Fix: Retry logic

- src/lib/_navigation.scss
Made the navigation buttons skinner, in particular the next file navigation button, in order to allow room for the preview content scrollbar to be clickable
> Fix: navigation buttons shouldn't cover scrollbar

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/events.js
Allows for file info to be request external to preview, and still report timings. 
*Note: Updates are required in Box UI Elements before this can be merged, otherwise false reports will be generated.*
> Chore: Allow load metrics emission without file info

- src/lib/viewers/media/Dash.scss
- src/lib/viewers/media/MediaControls.scss
Issue is that on minimum sized videos, the video controls get too cramped once you max out the content to be displayed. This means that the video needs have a length in hours, not minutes, as well as close captioning as an option. This is only observed when the hover over the volume control expands out to the right. From experimenting, it appears that no matter how small the video is that is uploaded, the conversion upscales it to minimum 480p and when it's rendered is at least 420px wide.
Before:
After:
The fix was to set a min-width on the video element to be 460px which seems to be wide enough to comfortably render the volume slider, the time display in hours, and the CC button (along with the other default controls).
> Fix: add min-width to video

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageViewer.js
Instead of waiting for the Preview viewer to finish loading before constructing the Annotator (which fetches the annotations for the file) we construct the Annotator as soon as the BoxAnnotations static assets are loaded.
From testing on my computer, saw a slight boost of 200-300ms in loading preview with annotations with caching disabled (or about the time it takes to do a network roundtrip for the annotations call). With caching there wasn't much of a time difference since the BoxAnnotations assets were already fetched.
> Fix: construct annotator when BoxAnnotations loads

- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
This added test prevents future additions of non-standard headers
> Chore: Add test to check PDFjs headers to avoid preflight

- src/lib/_common.scss
Adding the tabindex caused the outline to appear on the preview container
> Chore: Remove outline from preview container

- src/lib/RepStatus.js
- src/lib/__tests__/RepStatus-test.js
- src/lib/constants.js
If representation does not yet exist for a file (status is 'none') don't delay in fetching rep in order to kick off conversion asap.
> Fix: Don't wait when rep status is none

- package.json
- yarn.lock
Will leave it at 2.3 until React Annotations bugs are fully resolved.
> Chore: Downgrade annotations to 2.3.0

- src/i18n/en-US.properties
- src/lib/icons/icons.js
- src/lib/icons/thumbnails-toggle-icon.svg
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/DocumentViewer.js
- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/DocumentViewer-test.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
> New: Thumbnails toggle button

- src/lib/Preview.js
- src/lib/Preview.scss
- src/lib/VirtualScroller.js
- src/lib/VirtualScroller.scss
- src/lib/constants.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/_docBase.scss
Unit tests to follow in separate PR
> New: Virtual scroll for the thumbnails sidebar

- src/lib/Preview.js
- src/lib/PreviewUI.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/PreviewUI-test.js
> Update: Continuous progress bar through retries

- src/lib/Preview.js
- src/lib/ThumbnailsSidebar.js
- src/lib/VirtualScroller.js
- src/lib/__tests__/VirtualScroller-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/_docBase.scss
> Update: Thumbnails sidebar images

- src/lib/ThumbnailsSidebar.js
- src/lib/VirtualScroller.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/_boxuiVariables.scss
- src/lib/viewers/doc/_docBase.scss
> Update: Handle non uniform thumbnail sizes

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Emits new viewer events `thumbnailsOpen` and `thumbnailsClose` when the thumbnails sidebar is toggled opened and closed.
> Update: Emit thumbnails[Open|Close] viewer event

- src/lib/VirtualScroller.js
- src/lib/__tests__/VirtualScroller-test.js
Changed the strategy from re-creating the `ol` on each render, to manipulating the individual `li` (creating new ones and deleting the old ones outside the "window" into the list). 
This is because Safari wasn't smart about the cloned elements in the previous strategy and would cause a flicker of the thumbnails on each `renderItems` call
> Update: Change VirtualScroller.renderItems strategy

- README.md
- build/webpack.config.js
- package.json
- src/index.html
- yarn.lock
Note: The test file has to live inside `/src` so it can access the `/src/third-party` assets.
> Chore: Add webpack-dev-server to support local development

- package.json
- yarn.lock
https://github.com/box/box-annotations/releases/tag/v3.7.1
* Update Translations (#328) ([39805b8](box/box-annotations@39805b8)), closes [#328](box/box-annotations#328)
* Chore: Add escape hotkey on AnnotationPopover (#327) ([e92ec85](box/box-annotations@e92ec85)), closes [#327](box/box-annotations#327)
* Fix: Highlight selection on Surface (#326) ([6a3b83a](box/box-annotations@6a3b83a)), closes [#326](box/box-annotations#326)
* Fix: Import correct styling for flyout component (#325) ([14d65f6](box/box-annotations@14d65f6)), closes [#325](box/box-annotations#325)
* Fix: Creation of highlights on Edge/IE11/Firefox browsers (#322) ([3d9ee7f](https://github.com/box/box-annotations/commit/3d9ee7f)), closes [#322](https://github.com/box/box-annotations/issues/322)
* Docs: Update badges (#324) …
> Update: box-annotations to v3.7.1

- src/lib/ThumbnailsSidebar.js
- src/lib/VirtualScroller.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/__tests__/VirtualScroller-test.js
Two changes here:
1. Serially render the thumbnail images
2. Expanded the `thumbnailImageCache` to mark when a thumbnail image has been requested in order to avoid multiple thumbnail images being created
> Update: Serially render thumbnail images

- src/lib/ThumbnailsSidebar.js
- src/lib/VirtualScroller.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/__tests__/VirtualScroller-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
> Update: Scroll into view

- src/lib/_common.scss
- src/lib/shell.html
- src/lib/viewers/doc/_docBase.scss
* Re-enables keyboard nav while in fullscreen
* Hides the toggle thumbnail button from the document controls while in fullscreen because thumbnail sidebar is not visible anyway
* applies a `min-width` to the `.bp-content` div so that fullscreen works in Safari
> Chore: Fix fullscreen nav and hide toggle thumbnail button

- src/lib/_loading.scss
- src/lib/_navigation.scss
- src/lib/shell.html
Fixes the issue where the file navigation buttons were not clickable while the viewer was loading.
The issue is that before the viewer is loaded `pointer-events: none` is applied to `.bp` div and is inherited by all the descendants except for the `.bp-loading-wrapper` child which sets `pointer-events: all` and `z-index: 1` (to appear above the viewer div). 
The solution here is to move the `.bp-loading-wrapper` inside of `.bp-content` instead of being a peer and override the `pointer-events` property on the navigation buttons so that they're always clickable
> Chore: Move loading wrapper inside bp-content

- package.json
- yarn.lock
Addressing the security alerts for `cryptiles` and `merge`.
`cryptiles` is a nested dependency of `webdriverio` which was for codeceptjs which was already removed so this can be removed as well.
`merge` is a nested dependency of `mojito-rb-gen`
> Chore: Address Security updates

- src/lib/api.js
For some reason, when specifying `responseType: 'text'` axios still returns the response data as parsed json, so adding a `transformResponse` option to get the text back for PlainTextViewer content
> Fix: Get response as text from axios

- src/index.html
- src/lib/events.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- test/integration/sanity/DeletedReps.e2e.test.js
> Fix: Fail gracefully when previewing a doc with deleted reps

- src/lib/ThumbnailsSidebar.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/viewers/doc/_docBase.scss
> Update: Add hover state to thumbnails

- src/lib/viewers/doc/_docBase.scss
TIL that animations defined within a media query don't work in IE11 ([source - known issues tab](https://caniuse.com/#search=keyframe)).
>IE10 and IE11 do not support CSS keyframe blocks inside media queries. Must be defined outside of media query definitions
> Fix: Thumbnail navigation now animates correctly in IE11

- src/lib/ThumbnailsSidebar.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.html
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- test/integration/document/Thumbnails.e2e.test.js
Will open the Preview Thumbnails by default for document viewers. Will also remember on a per file basis (via `localStorage`) the toggle state of the thumbnails sidebar.
Todo:
> Update: Open Preview Thumbnails by default

- src/lib/VirtualScroller.js
- src/lib/__tests__/VirtualScroller-test.js
- test/integration/document/Thumbnails.e2e.test.js
Also updated `VirtualScroller.isVisible` logic to account for the whole height of the item instead of just the `offsetTop`.
> Fix: On Thumbnails initial render, scroll item into view

- src/lib/viewers/doc/_docBase.scss
This fixes an issue in ie11 where a black section appears on the left in fullscreen while the thumbnails sidebar is toggled open
> Fix: Position bp-content left in fullscreen

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/media/_mediaBase.scss
- src/lib/viewers/office/OfficeViewer.js
- src/lib/viewers/office/__tests__/OfficeViewer-test.js
- src/lib/viewers/text/PlainTextViewer.js
- src/lib/viewers/text/__tests__/MarkdownViewer-test.js
- src/lib/viewers/text/__tests__/PlainTextViewer-test.js
Print popup is now centered with respect to the `.bp` div
Previously:
Now:
Also adjusted media styles for `bp-is-buffering`
TODO:
> Fix: Print poup and buffering DOM references

- src/lib/viewers/image/ImageBaseViewer.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/MultiImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
- src/lib/viewers/image/__tests__/MultiImageViewer-test.js
- test/integration/sanity/DeletedReps.e2e.test.js
This change reverts portions of https://github.com/box/box-content-preview/pull/964 due to an issue where XHRs to cached image files are throwing CORS errors in the Embed Widget.
> Fix: Load images via img elements to avoid CORS issues with XHRs

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
The next/previous buttons currently don't show at all when previewing a collection with files that produce an error (such as unsupported, password protected, etc.).
> Fix: Show next/previous buttons for file collections in error viewer

- src/lib/viewers/media/Dash.scss
- src/lib/viewers/media/_mediaBase.scss
It looks like vertical videos are affected due to a min-width set on the video element which maintains its aspect ratio on narrow screens. Unfortunately, this causes the media controls to overflow past the edge of the viewport.
> Fix: Media controls now visible for videos in narrow window

- src/lib/viewers/media/Dash.scss
- src/lib/viewers/media/MP4.scss
- src/lib/viewers/media/_mediaBase.scss
The previous change caused videos to render at their natural height, even in fullscreen, rather than allowing them to expand. This change will center the video element without affecting its displayed size or ability to expand while still limiting it and its controls to a minimum width of 300 pixels.
> Fix: Center video element and maintain its size and ratio

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
The initial resize may happen before the document is ready, so resizing when we decleare the document 'loaded' will ensure that the PDF is resized, not the preload image. The initial resize is preserved so that preload image will be resized when the thumbnails open.
> Fix: Resize preview when thumbnails open

- src/i18n/en-US.properties
- src/lib/PreviewUI.js
- src/lib/__tests__/metadataAPI-test.js
- src/lib/constants.js
- src/lib/metadataAPI.js
- src/lib/viewers/doc/AutoCADViewer.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/DocLoader.js
- src/lib/viewers/doc/__tests__/AutoCADViewer-test.js
> New: Show banner when doc has xrefs

- src/lib/events.js
- src/lib/metadataAPI.js
- src/lib/viewers/doc/AutoCADViewer.js
- src/lib/viewers/doc/DocLoader.js
- src/lib/viewers/doc/__tests__/AutoCADViewer-test.js
When dwg file has missing external references, will emit an event `missing_x_refs` with file extension as the data
> New: Emit metric when missing xrefs

- src/i18n/en-US.properties
- src/lib/Notification.js
- src/lib/PreviewUI.js
- src/lib/__tests__/Notification-test.js
- src/lib/__tests__/PreviewUI-test.html
- src/lib/__tests__/PreviewUI-test.js
- src/lib/_boxui.scss
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/doc/DocPreloader.js
- src/lib/viewers/doc/__tests__/DocPreloader-test.js
In PreviewUI.js, introduced `previewContainer` which points to `.bp` div. Existing `contentContainer` (which used to point to `.bp`) is now `.bp-content` which is only used for Notification.js
Also changed the default "Okay" to use the `close.svg`
> Fix: Move notification to be child of preview content

- src/lib/viewers/media/MediaControls.scss
1. Adding bg color on hover for CC button doesn't play nicely on mobile devices.
2. Other buttons in media player don't have bg color on hover.
3. When CC is turned off, user doesn't know because the button is still blue because of the hover effect.
Removing `:hover` style solves all the above issues.
> Fix: Remove bg color for cc button on hover

- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
* Add listener that is fired once the iframe has loaded it's content for printing.
This enables chrome to show an accurate print preview.
> Fix: Chrome Print Preview Fix

- CHANGELOG.md
- CONTRIBUTING.md
- HISTORY.md
- README.md
- UPGRADING.md
- build/release.sh
- package.json
- yarn.lock
We should consider moving to semantic-release in the future, but that will require additional effort. I also ran all the MD files through prettier since they're modified during release.
> build(release): Update conventional-github-releaser to latest

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/DocFindBar.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/DocFindBar-test.js
Currently, users are forced to click the document pane after closing the find bar to re-open it or scroll through the content with the keyboard. We also prevent the browser find bar from opening if the user doesn't have download permissions, which is unnecessary, as the text layer doesn't exist.
> fix(find): Prevent loss of focus on content when find bar is closed

- build/karma.conf.js
Re-enable the ability to do `yarn test -- --src=viewers/text/CSVViewer` and have it run just the CSVViewer-test.js instead of all the unit tests
> chore: Re-enable running karma tests for a single test file

- src/lib/events.js
- src/lib/viewers/box3d/video360/__tests__/Video360Viewer-test.js
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/__tests__/DashViewer-test.js
- src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
- src/lib/viewers/media/__tests__/VideoBaseViewer-test.js
Introduces two new metric events:
-  `media_metric_buffer_fill` which represents the initial buffering before playback can begin
- `media_metric_end_playback` which contains metrics around total buffering time, lag/watch ratio, etc...
`media_metric_buffer_fill` will be emitted as soon as it is measured.
`media_metric_end_playback` will be emitted in 3 scenarios:
1. when playback is finished (`ended` event is fired)
2. when the viewer is destroyed (when preview is closed)
3. when the page unloads
As part of this PR, only the `DashViewer` will emit these metrics.
TODO:
> feat(dashviewer): Video performance instrumentation

- src/lib/constants.js
- src/lib/viewers/text/CSV.scss
- src/lib/viewers/text/PlainTextViewer.js
- src/lib/viewers/text/Text.scss
- src/lib/viewers/text/TextBaseViewer.js
- src/lib/viewers/text/__tests__/TextBaseViewer-test.js
- src/lib/viewers/text/_base.scss
I also tried to consolidate and improve the logic for text selection.
> fix(text): Hide print content for users without download permission

- src/i18n/en-AU.properties
- src/i18n/en-CA.properties
- src/i18n/en-GB.properties
- src/i18n/en-US.properties
- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/PreviewError-test.js
- src/lib/constants.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DLoader-test.js
- src/lib/viewers/error/PreviewErrorViewer.js
- src/lib/viewers/media/__tests__/MediaLoader-test.js
- test/integration/document/Thumbnails.e2e.test.js
- test/integration/sanity/Download.e2e.test.js
for when download might get disabled due to an access policy while the user is already previewing the file without browser refresh.
Also fixes the apostrophes
> fix(download): show appropriate download error

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/events.js
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
Will add tests later. The related BUIE change: https://github.com/box/box-ui-elements/pull/1689
> fix(mediaviewer): Refresh token if token expired

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
When PDFjs updates the page scaling, it emits the `pagerendered` event, so this PR moves the logic to update the zoom control with the current scale value based off of that event. This covers the issue where toggling fullscreen wouldn't update the current scale value in the zoom control.
> fix(doc zoom): Move zoom control update to pagerender handler

- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
It seems that PresentationViewer was written before the PDFSinglePageViewer was available. The original implementation included several hacks to override core PDF.js functionality around scroll, which broke with our upgrade in August. This change should resolve that bug and simplifies the viewer's logic.
> fix(viewer): Find controls in PPT files update current page

- src/lib/viewers/image/ImageBaseViewer.js
The `parseFromString` method can throw errors in IE11 if the source SVG XML is malformed. The resulting image has no `originalSize` attribute, allowing it to expand to the size of the viewport and interfering with the new zoom behavior.
> fix(viewer): Set default size on SVG images if parsing fails in IE11

- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
This change reverts #1101 due to issues with box-annotations, which relies on every page being rendered in the DOM, even if it's not yet visible. Find controls still work properly with this change. I renamed PresentationViewer's `pagechangeHandler` to `pagechangingHandler` so the base method is overridden properly, which was the original bug that #1101 was meant to address.
> fix(viewer): Annotations render correctly for presentation files

- src/lib/ThumbnailsSidebar.js
This change is to fix a sanity test. The function `createThumbnailImage` is used as a callback. Maybe the object has been destroyed before the callback happens. So we need to check whether `this.thumbnailImageCache` still exists.
> fix(test): Fix possible sanity test bug

- src/i18n/en-US.properties
- src/lib/viewers/archive/ArchiveExplorer.js
- src/lib/viewers/archive/ArchiveExplorer.scss
- src/lib/viewers/archive/Breadcrumbs.js
- src/lib/viewers/archive/Breadcrumbs.scss
- src/lib/viewers/archive/__tests__/ArchiveExplorer-test-react.js
- src/lib/viewers/archive/__tests__/Breadcrumbs-test-react.js
- src/lib/viewers/archive/constants.js
Demo video: https://cloud.box.com/s/wsfhibzz9a1uyjt3uhs88j8kz75nnlgf
> feat(archive-viewer): add breadcrumbs

- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
Fixes an issue with Safari not showing videos on MacOS Catalina
> fix(video): Change event type for setting up video element

- src/lib/__tests__/Preview-test.js
- src/lib/constants.js
- src/lib/loaders.js
If conversion feature flip is not enabled for a user, the user will see the error message "We're sorry, your account is unable to preview this file type."
> feat(archive): Add archive loader to prepare for conversion feature flip

- src/lib/viewers/archive/SearchBar.js
- test/integration/archive/ArchiveViewer.e2e.test.js
- test/support/constants.js
The test is failing because conversion feature flip is not on for our e2e test account. The account is live, so we have to wait until the next week. The test works on my dev vm.
> test(archive): Add e2e test

- src/lib/viewers/archive/ArchiveExplorer.js
- src/lib/viewers/archive/__tests__/ArchiveExplorer-test-react.js
* Add try/catch handler for exceptions
* Handle case when sorting data is falsy
> fix(archive): Fix blank screen when sorting

- .nvmrc
- .travis.yml
- README.md
- package.json
- yarn.lock
This change also upgrades node-sass to avoid issues with Node 12.
> chore(deps): Upgrade node and yarn version requirements

- src/lib/viewers/archive/SearchBar.scss
> fix(archive): Fix inconsistent search bar style on mobile devices

- src/lib/viewers/archive/Breadcrumbs.scss
> fix(archive): Fix truncated breadcrumb when file name is too long

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
The webkit bug was fixed on Jan 2018. I removed the header and tried to preview a pdf file on iOS 12.0 and iOS 13.3 (We only support two latest released versions), and they both work well. So I'm gonna remove the unnecessary http header code for iOS.
> fix(doc): Remove unnecessary http header for iOS

- package.json
- src/lib/viewers/archive/ArchiveExplorer.js
- src/lib/viewers/archive/__tests__/ArchiveExplorer-test-react.js
- test/integration/archive/ArchiveViewer.e2e.test.js
- yarn.lock
> fix(archive): Folders come before files when sorting

- src/lib/AnnotationControls.ts
- src/lib/__tests__/AnnotationControls-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Updated the create event to `annotations_create` and added logic to `toggleAnnotationMode` and set the active annotation id in the annotator
Todo:
> feat(annotation): handle create event

- src/lib/__tests__/i18n-test.js
- src/lib/i18n.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
* Add support for annotation options
* Use messages and locale if preset in options and forward them to the annotator to populate messages and locale
> feat(annotations): add support for passed annotations options

- src/lib/Controls.js
- src/lib/__tests__/Controls-test.js
* Stop event propagation from preview controls, this is interfering with annotations.
* Add new tests for Controls.js constructor
> fix(controls): stop event propagation from controls

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
* Add handler to handle the scrolltoannotation event.
* Add override to PresentationViewer to setPage since we only show 1 page at a time.
> fix(annotations): handle scrollToAnnotation in Preview

- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
This change prevents the scroll position from being reset if the user has zoomed in and selects multiple annotations on the same page.
> fix(annotations): Scroll to presentation page only when necessary

- src/lib/AnnotationControls.ts
- src/lib/Controls.js
- src/lib/__tests__/AnnotationControls-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
> chore(resin): Add annotations resin tags

- src/lib/viewers/doc/DocFindBar.scss
- src/lib/viewers/doc/_docBase.scss
Updated text selection background-color to box blue with 10% opacity
Before:
After:
> feat(doc): Updated text selection color

- src/lib/Preview.js
- src/lib/Timer.js
- src/lib/__tests__/Timer-test.js
- src/lib/events.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
> feat(perf): Add support for document viewer performance options

- src/lib/AnnotationControls.ts
- src/lib/AnnotationControlsFSM.ts
- src/lib/AnnotationFSM.ts
- src/lib/__tests__/AnnotationControls-test.js
- src/lib/__tests__/AnnotationControlsFSM-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
> feat(annotations): Handle annotations staged change event

- src/lib/AnnotationControlsFSM.ts
- src/lib/__tests__/AnnotationControlsFSM-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Prerequisite: https://github.com/box/box-annotations/pull/588
> feat(annotations): Handle annotations creator status change event

- src/lib/Preview.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
> feat(annotations): Set region as default mode if discover FF is on

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Pay attention to the cursor
Before:
After:
> fix(annotations): Fix cursor when drawing region in default mode

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
> fix(discoverability): set mode to REGION instead of NONE

- src/lib/constants.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/_annotations.scss
- src/lib/viewers/doc/_docBase.scss
When in explicit annotation creation mode (highlight or region), all existing annotation targets should not be interact-able.
> feat(annotations): Disable target pointer-events when explicit creation

- src/lib/AnnotationControlsFSM.ts
- src/lib/__tests__/AnnotationControlsFSM-test.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
> fix(discoverability): set mode to REGION on escape key press

- src/lib/__tests__/AnnotationControlsFSM-test.js
- src/lib/__tests__/Controls-test.js
- src/lib/__tests__/Preview-test.js
- src/lib/__tests__/i18n-test.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/box3d/__mocks__/Box3DRuntime.js
- src/lib/viewers/box3d/__tests__/Box3DRenderer-test.js
- src/lib/viewers/box3d/image360/__tests__/Image360Renderer-test.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DControls-test.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DRenderer-test.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DViewer-test.js
- src/lib/viewers/box3d/video360/__tests__/Video360Controls-test.js
- src/lib/viewers/box3d/video360/__tests__/Video360Renderer-test.js
- src/lib/viewers/box3d/video360/__tests__/Video360Viewer-test.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/__tests__/ImageBaseViewer-test.js
- src/lib/viewers/image/__tests__/ImageLoader-test.js
There are still 11 troublesome tests that are marked as skipped, but I'm going to set them aside for now. I think 2561/2572 tests passing is good enough for now.
> test(jest): Convert the remaining 3D viewer unit tests to Jest

- src/lib/viewers/doc/_docBase.scss
> fix(annotations): Fix text blocked by old highlight selection background

- src/lib/constants.js
We found a font rendering regression when previewing large documents in Microsoft Edge via VM. There appears to be an emerging rendering issue with the latest version of pdf.js in resource-constrained environments. We'll need to revert to the prior working version until it's resolved.
> fix(pdf): Revert pdf.js to v2.2.228 due to font rendering issue

- src/lib/constants.js
> fix(annotations): remove bp prefix from region cursor keys

- src/lib/AnnotationModule.ts
- src/lib/viewers/controls/annotations/DrawingControls.tsx
- src/lib/viewers/controls/annotations/__tests__/DrawingControls-test.tsx
- src/lib/viewers/controls/controls-bar/ControlsBar.tsx
- src/lib/viewers/controls/controls-bar/__tests__/ControlsBar-test.tsx
- src/lib/viewers/doc/DocControls.tsx
- src/lib/viewers/image/ImageControls.tsx
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
**Changes in this PR:**
**Demo:**
> feat(drawing): add ColorPickerControl for images

- src/lib/viewers/controls/color-picker/ColorPickerControl.tsx
Changes in this PR:
Note: We aren't adding any additional key handling (left / right arrows) as I think the current tabbing experience is satisfactory for complete navigation through the color picker elements
> fix(drawing): fix accessibility for color picker components

- src/lib/constants.js
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
Annotations part: https://github.com/box/box-annotations/pull/653/files
> feat(annotations): Emit annotations color

- src/lib/viewers/controls/findbar/FindBarToggle.tsx
- src/lib/viewers/controls/findbar/__tests__/FindBarToggle-test.tsx
- src/lib/viewers/controls/sidebar/ThumbnailsToggle.tsx
- src/lib/viewers/controls/sidebar/__tests__/ThumbnailsToggle-test.tsx
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
I chose to short-circuit the toggles if their callback is undefined to avoid further prop sprawl on the DocControls component.
> fix(controls): Hide find and thumbnail toggles if options are disabled

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
**Issue:**
If the user updates the drawing color in the first browser tab (when there are two tabs open), the cursor color will be stale in the second tab. The proposed fix is to emit the color change event every time the Color Picker is opened - this will ensure that the cursor color matches the color in the Preview Toolbar.
**Changes in this PR:**
**Demo:**
> fix(drawing): emit color event when color picker is opened

- src/lib/viewers/controls/controls-layer/ControlsLayer.tsx
- src/lib/viewers/controls/controls-layer/__tests__/ControlsLayer-test.tsx
Prevents a console error in development mode.
> fix(controls): Prevent controls from hiding when already unmounted

- src/lib/viewers/controls/color-picker/ColorPickerControl.scss
- src/lib/viewers/controls/color-picker/ColorPickerControl.tsx
- src/lib/viewers/controls/color-picker/__tests__/ColorPickerControl-test.tsx
**Changes in this PR:**
**Demo:**
**Chrome**
**Safari**
**FF**
**Edge**
**IE**
> fix(drawing): show sub-shadow in color picker control button

- src/lib/viewers/controls/color-picker/ColorPickerControl.tsx
- src/lib/viewers/controls/color-picker/__tests__/ColorPickerControl-test.tsx
> fix(annotations): Fix user cannot tab to color picker

- src/lib/VirtualScroller.js
- src/lib/__tests__/VirtualScroller-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
I considered polyfilling the method on the Element prototype, but decided against it to avoid further altering global objects.
> fix(thumbnails): Replace remove method that is unsupported in IE11

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/viewers/controls/media/DurationLabels.scss
- src/lib/viewers/media/MP3Controls.scss
- src/lib/viewers/media/MP3Controls.tsx
- src/lib/viewers/media/MP3Viewer.js
- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/MediaControlsRoot.scss
- src/lib/viewers/media/MediaControlsRoot.tsx
- src/lib/viewers/media/__tests__/MP3Controls-test.jsx
- src/lib/viewers/media/__tests__/MP3Viewer-test.js
- src/lib/viewers/media/__tests__/MediaBaseViewer-test.js
- src/lib/viewers/media/__tests__/MediaControlsRoot-test.tsx
> feat(controls): Add react version of mp3 controls behind option

- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsMenuBack.scss
- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsMenuBack.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsMenuItem.scss
- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsMenuItem.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsRadioItem.scss
- src/lib/viewers/controls/media/MediaSettingsControls/MediaSettingsRadioItem.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/__tests__/MediaSettingsContext-test.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/__tests__/MediaSettingsMenuBack-test.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/__tests__/MediaSettingsMenuItem-test.tsx
- src/lib/viewers/controls/media/MediaSettingsControls/__tests__/MediaSettingsRadioItem-test.tsx
Continuing the changes mentioned in #1340. In my opinion, while these components are similar, they are different enough that sharing logic and/or markup between them would be somewhat awkward. I'm open to feedback and suggestions, though.
> feat(controls): Add media settings control item components

- src/lib/viewers/image/ImageViewer.js
- src/lib/viewers/image/__tests__/ImageViewer-test.js
- Adds alt attribute to preview images in order to be a11y compliant.
> fix(a11y): Add meaningful alt text to image viewer

- src/lib/ThumbnailsSidebar.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/viewers/doc/_docBase.scss
- src/lib/viewers/doc/_theme.scss
I included the `custom-theme` styles in this PR to avoid any issues with unsynchronized releases. We can move them in a follow-up, if desired.
> feat(thumbnails): Update document thumbnails to latest designs

- src/lib/viewers/controls/_styles.scss
Firefox in Windows evidently allows focus for buttons that are disabled, so we need to adjust the styles to account for it.
> fix(controls): Avoid showing focus styles for disabled controls

- src/lib/viewers/doc/_docBase.scss
I'm adding this override here to simplify the release coordination between Preview SDK and BUIE. We can move it to BUIE proper and remove the `!important` once this release is being used in production. I'm open to other suggestions, as well.
> fix(thumbnails): Fix position of ContentPreview navigate button

- src/lib/viewers/doc/Document.scss
- src/lib/viewers/doc/Presentation.scss
- src/lib/viewers/doc/_docBase.scss
- src/lib/viewers/doc/_loading.scss
- src/lib/viewers/doc/_mixins.scss
**Page Shadows**
**Preloader Shadows**
**Placeholder Shadows**
> feat(documents): Add drop shadow for document pages and placeholders

- src/lib/Preview.js
- src/lib/viewers/box3d/Box3DViewer.js
- src/lib/viewers/box3d/__tests__/Box3DViewer-test.js
- src/lib/viewers/box3d/model3d/Model3DControlsNew.tsx
- src/lib/viewers/box3d/model3d/Model3DViewer.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DControlsNew-test.tsx
- src/lib/viewers/box3d/model3d/__tests__/Model3DViewer-test.js
- src/lib/viewers/controls/icons/IconAnimation24.tsx
- src/lib/viewers/controls/icons/IconReset24.tsx
- src/lib/viewers/controls/model3d/AnimationClipsControl.tsx
- src/lib/viewers/controls/model3d/AnimationClipsToggle.scss
- src/lib/viewers/controls/model3d/AnimationClipsToggle.tsx
- src/lib/viewers/controls/model3d/AnimationControls.scss
- src/lib/viewers/controls/model3d/AnimationControls.tsx
- src/lib/viewers/controls/model3d/ResetControl.scss
- src/lib/viewers/controls/model3d/ResetControl.tsx
Initial React rewrite of Model3DViewer controls
TODO:
Before:
After:
> feat(model3d): Basic React controls

- src/i18n/en-US.properties
- src/lib/viewers/box3d/model3d/Model3DControlsNew.tsx
- src/lib/viewers/box3d/model3d/Model3DViewer.js
- src/lib/viewers/box3d/model3d/__tests__/Model3DControlsNew-test.tsx
- src/lib/viewers/box3d/model3d/__tests__/Model3DViewer-test.js
- src/lib/viewers/controls/model3d/Model3DSettings.scss
- src/lib/viewers/controls/model3d/Model3DSettings.tsx
- src/lib/viewers/controls/model3d/RotateAxisControl.scss
- src/lib/viewers/controls/model3d/RotateAxisControl.tsx
- src/lib/viewers/controls/model3d/RotateAxisControls.scss
- src/lib/viewers/controls/model3d/RotateAxisControls.tsx
- src/lib/viewers/controls/model3d/__tests__/Model3DSettings-test.tsx
- src/lib/viewers/controls/model3d/__tests__/RotateAxisControl-test.tsx
- src/lib/viewers/controls/model3d/__tests__/RotateAxisControls-test.tsx
- src/lib/viewers/controls/settings/Settings.tsx
- src/lib/viewers/controls/settings/SettingsDropdown.scss
- src/lib/viewers/controls/settings/SettingsDropdown.tsx
- src/lib/viewers/controls/settings/__tests__/Settings-test.tsx
- src/lib/viewers/controls/settings/__tests__/SettingsDropdown-test.tsx
> feat(controls): Add Settings menu to Model3D

- src/lib/types/react-augment.d.ts
- src/lib/viewers/controls/settings/SettingsCheckboxItem.tsx
- src/lib/viewers/controls/settings/SettingsDropdown.scss
- src/lib/viewers/controls/settings/SettingsDropdown.tsx
- src/lib/viewers/controls/settings/__tests__/SettingsDropdown-test.tsx
Fixes an issue where a console error occurs when opening the `Model3DSettings` menu because `SettingsList` attempts to set focus to the menu item that correlates to the `activeIndex`. Since `SettingsDropdown` and `SettingsCheckboxItem` are functional components, an error is logged.
TODO:
> fix(controls): Add forwardRef to Dropdown and Checkbox

- src/lib/viewers/controls/media/_styles.scss
- src/lib/viewers/media/Dash.scss
- src/lib/viewers/media/DashControls.scss
- src/lib/viewers/media/DashControls.tsx
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MP4.scss
- src/lib/viewers/media/MP4Controls.scss
- src/lib/viewers/media/__tests__/DashControls-test.tsx
- src/lib/viewers/media/__tests__/DashViewer-test.js
- src/lib/viewers/media/_mediaBase.scss
> feat(controls): Base React controls for Dash

- src/lib/viewers/controls/media/MediaSettings.tsx
- src/lib/viewers/controls/media/MediaSettingsAudioTracks.tsx
- src/lib/viewers/controls/media/__mocks__/audioTracks.ts
- src/lib/viewers/controls/media/__tests__/MediaSettings-test.tsx
- src/lib/viewers/controls/media/__tests__/MediaSettingsAudioTracks-test.tsx
- src/lib/viewers/controls/settings/SettingsContext.ts
- src/lib/viewers/media/DashControls.tsx
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/__tests__/DashControls-test.tsx
- src/lib/viewers/media/__tests__/DashViewer-test.js
> feat(controls): Audio tracks menu for Dash viewer

- src/lib/viewers/doc/Presentation.scss
- src/lib/viewers/doc/_docBase.scss
The Presentation viewer creates all pages of a document as a big stack of elements using absolute positioning. It controls the page elements' visibility via the `visibility` style directive. However, unlike other browsers, Safari 14 on MacOS Big Sur seems to frequently layout/paint every page of the document, even if the page has `visibility: hidden` set. Adding `opacity: 0` seems to resolve the problem.
> perf(presentation): Improve presentation rendering performance in Safari

- src/lib/constants.js
- src/lib/viewers/controls/media/MediaSettings.tsx
- src/lib/viewers/controls/media/MediaSettingsAudioTracks.tsx
- src/lib/viewers/controls/media/MediaSettingsMenuQuality.tsx
- src/lib/viewers/controls/media/MediaSettingsMenuSubtitles.tsx
- src/lib/viewers/controls/media/SubtitlesToggle.scss
- src/lib/viewers/controls/media/SubtitlesToggle.tsx
- src/lib/viewers/controls/media/__mocks__/subtitles.ts
- src/lib/viewers/controls/media/__tests__/MediaSettings-test.tsx
- src/lib/viewers/controls/media/__tests__/MediaSettingsAudioTracks-test.tsx
- src/lib/viewers/controls/media/__tests__/MediaSettingsMenuQuality-test.tsx
- src/lib/viewers/controls/media/__tests__/MediaSettingsMenuSubtitles-test.tsx
- src/lib/viewers/controls/media/__tests__/SubtitlesToggle-test.tsx
- src/lib/viewers/media/DashControls.tsx
- src/lib/viewers/media/DashViewer.js
- src/lib/viewers/media/MediaControls.html
- src/lib/viewers/media/__tests__/DashControls-test.tsx
- src/lib/viewers/media/__tests__/DashViewer-test.js
> feat(controls): Add Subtitles menu for Dash

- src/lib/ThumbnailsSidebar.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
There is a visual indication of the current thumbnail that also presents the current page You should convey this information to screen reader with aria-current="true". For example:
<div class="bp-thumbnail bp-thumbnail-is-selected bp-thumbnail-image-loaded" data-bp-page-num="7" role="button" aria-current="true">
> fix(ThumbnailsSidebar): A11Y - add aria-current to ThumbnailsSidebar

- src/lib/viewers/controls/findbar/FindBarToggle.tsx
- src/lib/viewers/controls/findbar/__tests__/FindBarToggle-test.tsx
- src/lib/viewers/doc/DocBaseViewer.js
When the findBar is closed the focus should go back to the find toggle button located on toolbar.
> Wrong focus on close findbar

- src/lib/viewers/BaseViewer.js
- src/lib/viewers/controls/fullscreen/FullscreenToggle.tsx
- src/lib/viewers/controls/fullscreen/__tests__/FullscreenToggle-test.tsx
When the fullscreen is toggled the focus should go back to the fullscreen toggle button located on toolbar.
> fix(a11y): wrong focus selection on toggleFullscreen method

- src/lib/viewers/iframe/IFrameLoader.js
- src/lib/viewers/iframe/__tests__/IFrameLoader-test.js
- src/lib/viewers/iframe/__tests__/IFrameViewer-test.js
Removes preview support for boxdicom files. This is a prerequisite for modifying the default behavior to opening boxdicom files with Ambra.
> feat(viewer): Add support for disabling .boxdicom file type

- src/lib/viewers/iframe/IFrameLoader.js
- src/lib/viewers/iframe/__tests__/IFrameLoader-test.js
Uses the unsupported file type error message instead of the account error message for Box Dicom files.
> feat(viewer): use unsupported file type error message for .boxdicom

- src/lib/FocusTrap.ts
- src/lib/__tests__/FocusTrap-test.html
- src/lib/__tests__/FocusTrap-test.ts
- src/lib/types/global.ts
- src/lib/viewers/BaseViewer.js
- src/lib/viewers/__tests__/BaseViewer-test.js
Adds `FocusTrap` class which takes an element and allows you to `enable` or `disable` focus trapping.
This class is used for when Preview enters fullscreen to constrain tab navigation to within the visible previewed content. This can also be applied to the print modal.
TODO:
> feat(viewer): Add focus trap for fullscreen

- src/lib/viewers/doc/_docBase.scss
Remove zoom controls on touch devices with small-medium screen widths (<767px). Touch devices in this case refer to mobile. However, mobile seems more like a subset of touch devices to me. Perhaps this is an edge case we can ignore. 
https://zpl.io/dxDDLEp
> feat(annotations): remove zoom ctrls on mobile

- src/lib/_common.scss
Fixed an issue with the pseudo-fullscreen mode on ios iphone. Fullscreen APIs are not supported on that os+device combo. The pseudo-fullscreen mode broke some time ago and was no longer usable
The Fullscreen class adds "bp-fullscreen-unsupported" class and the corresponding CSS that applied the fullscreen styling did not select the correct element. Additionally, it would also appear under elements such as the header and sidebar elements, so I had to bump the z-index up
iOS iPhone psuedo-fullscreen mode bug
Fixed
This supercedes https://github.com/box/box-content-preview/pull/1452 which hides the Fullscreen node toggle for unsupported devices
> fix(fullscreen): fix fullscreen mode for ios/iphone combo

- package.json
- src/lib/viewers/doc/_docBase.scss
- yarn.lock
Note: Please approve https://github.com/box/box-content-preview/pull/1448 first
This is hidden on smaller modalities in order to prioritize other functions
https://zpl.io/dxDDLEp
> feat(thumbnails): remove thumbnail toggle on small modalities

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
Issue was introduced with latest 2.91 release
How to reproduce:
1. Open a Preview for any file.
2. Wait until the 2.0/events  request start, but go back before the request is finished
3. The code will enter in a state of sending those events in a loop state
Proposed change should fix this behaviour.
> fix(content-insights): events recurrent request issue

- src/i18n/en-US.properties
- src/lib/viewers/doc/DocBaseViewer.js
Recommendation was to remove tabindex and aria label 'Press alt + arrow keys...' text since it is not accurate for Windows computers, and it will not help keyboard users who are not using a screen reader. 
> fix(a11y): remove instructions

- src/lib/viewers/controls/annotations/AnnotationsControls.scss
- src/lib/viewers/doc/DocFindBar.scss
Search (controls are clickable):
Highlight and Comment tooltip clickable:
Drawing Annotation works on text layer:
> feat(pdf): Fix search and highlight + comment tooltip

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
We noticed when upgrading to PDFJS v3.6.172, copy/paste did not work for text on pdfs. This is because in this new PDFJS version, the enum we were using to pass into the `textLayerMode`, had changed from `ENABLE_ENHANCE` to `ENABLE_PERMISSION`. In previous PDFJS versions, `ENABLE_ENHANCE` would be an option to enable textLayerMode and enhance the text selection (improve text selection across multiple lines). However they have deprecated this option as of `v3.0.279` as noted here: 
- https://github.com/mozilla/pdf.js/pull/15259
- https://github.com/mozilla/pdf.js/issues/15138
- https://github.com/mozilla/pdf.js/pull/15145
They have replaced this enum with a new option called `ENABLE_PERMISSION` which if passed in for `textLayerMode`, checks the permission flags set for the PDF document. So …
> fix(copy-paste-issue): PDFJS copy paste fix

- src/lib/VirtualScroller.js
- src/lib/__tests__/VirtualScroller-test.js
- src/lib/featureChecking.ts
Scrolling jumps to bottom of page on embedded multi-page previews
- Add `{ block: 'nearest' }` as param to [`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to prevent the parent scrollbar from jumping around
- Fix a type to pass lint check
> fix(preview): fix auto scroll issue with embed preview

- src/lib/viewers/controls/annotations/AnnotationsControls.scss
In v3.6.172 of PDFjs, a z-index styling was explicitly added to pdf_viewer.css: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.6.172/pdf_viewer.css. This styling was not present in the previous version of PDFjs that we're using: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.14.305/pdf_viewer.css and keeping this new styling causes issues with the other layers in preview (i.e. popup layer, highlighted layer, etc.). Updating styling for our layers resolves the issues that QA has discovered, but moving them to the box-annotations repo is preferable.
Have tested this change in the SDK with the stylings moved to box-annotations/linked with EUA.
> feat(pdf): Move annotation styling to box-annotations

- src/lib/viewers/controls/annotations/AnnotationsControls.scss
Per discussion with @bfoxx1906 , we decided this style should be kept with the SDK
> feat(pdf): Move annotation marker styling back to sdk

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/_docBase.scss
This change adds support for screen readers and allow to disable copying content for view only PDF documents.
In order to simplify things the "view only" permission was implemented using CSS and JS , which should hopefully suffice.
The advantage of this approach, as opposed to e.g. disabling the textLayer completely, is first of all that it ensures that document is accessible through a screen reader. Secondly this also ensures that searching still works correctly even in copy-protected documents.
This kind of copy-protection is not very strong and is also relatively easy to create some workarounds. Hence a simple solution, targeting "normal"-users rather than "advanced"-users is hopefully deemed acceptable here.
Demo - https://cloud.box.com/s/h9dg4g7bwxorp60qvfvqgu5trjx9v5q6
> fix(a11y): screen reader support for view only file preview

- src/lib/viewers/controls/controls-root/ControlsRoot.scss
The popup annotation layer, which comes before this controls layer in the HTML hierarchy, now has a z-index of 4 due to changes needed for the PDFjs upgrade - because of this, the popup annotation layer was covering this controls layer. This causes the E2E tests in box-annotations to fail. So to resolve this, we need to also bring the controls layer up to a z-index of 4. 
Ran this change with the E2E tests for box-annotations locally and it was passing.
> fix(pdf): Move controls layer above popup layer

- package.json
- src/lib/viewers/doc/_docBase.scss
Because of a change in a css rule in the latest version of [pdf_viewer.css ](https://github.com/mozilla/pdf.js/blob/v3.6.172/web/pdf_viewer.css#L162)we were not overriding the loadingIcon style's background image which caused the CDN to record a large number of 404's as a result.
> fix(pdf): override css missing asset

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
This pr introduces changes to cover ACI codebase with feature checking
> feat(aci): use feature check for aci

- build/jest/react-intl-mock.js
- build/webpack.common.config.js
- jest.config.js
- package.json
- src/lib/viewers/archive/ArchiveExplorer.js
- yarn.lock
IMPORTANT:
- Minimal set of changes to solve the problem. 
Changes:
1. `react-intl` lib has been upgrade to v^6.4.2
2. BUIE has been updated to v^20.0.0 
3. deprecated `addLocaleData` (react-intl/locale-data has been removed from react-intl) has been removed ([doc](https://formatjs.io/docs/react-intl/upgrade-guide-3x)).
4. I have to add resolution for react-intl to package.json file ( "**/react-intl/**/@types/react": "^17.0.2"). react-intl has set @types/react to version 16 || 17 || 18 (https://github.com/formatjs/formatjs/blob/main/package.json#L61) so yarn install the latest one, however @types/react 17 i 18 are incompatible. It caused a mismatch of types in some components.
---
Testing:
Make sure application and strings are not broken when language is changed. 
---
For more …
> feat: update to react-intl 6

- src/lib/viewers/doc/_docBase.scss
Fix highlighting text in Preview. This bug was introduced as a regression during PDF.js upgrade.
Inside this [commit](https://github.com/mozilla/pdf.js/commit/1b00511301840d413f3369f834999ee44d3dfa8d#diff-90b9c7e02c41b4051095250577f8dd385455429d67abe6bf360e13ef17d7fe19L26) PDF.js team removed `z-index:2` from `.textLayer` class which is causing a bug that user cannot highlight text when annotations are enabled.
2.108.0 version (current):
2.107.0 version:
> fix(preview): Fix highlighting text when performing click and drag

- README.md
context:
https://sansec.io/research/polyfill-supply-chain-attack
and since promises work in all modern browsers
> chore(docs): remove polyfill.io from README

- src/lib/viewers/error/PreviewErrorViewer.js
- src/lib/viewers/error/__tests__/PreviewErrorViewer-test.js
**Description**
Remove restriction such that preview will fetch the icon based on the extension from box-ui-elements when there is a preview error. Will rely on the logic there to return a default icon when one does not exist for the extension.
See: https://github.com/box/box-ui-elements/blob/1850977829e4888139462a6f65794b1cffc52a08/src/components/preview/previewIcons.ts#L183
**Screenshots**
> feat(preview-error): Display file icon based on extension for errors

- src/lib/Preview.js
- src/lib/__tests__/Preview-test.js
- src/lib/constants.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Box will automatically use accept-encoding header
This fixes a bug where gzip encoding wasn't available in accept-encoding list
> fix(docs): Remove gzip encoding query param 

- README.md
This PR fixes a typo in the build instructions where `yarn:build:prod` was incorrectly specified. The correct command syntax is `yarn build:prod`.
> Fix yarn build command syntax in installation instructions

- .nvmrc
- .travis.yml
- package.json
- src/lib/__tests__/Preview-test.js
- src/lib/i18n.js
- src/lib/viewers/box3d/video360/__tests__/Video360Viewer-test.js
- yarn.lock
Updated project to work with Nodejs 20.
Bumped resolution of `acorn` to most recent as with node update it's older version stops working properly with optional chaining operators. The proper solution is to update Webpack to next version which should be handled in another task.
Removed IE 11 compatibility. Due to side effect, constructor mocks with arrow functions stopped working (were transcribed before).
> feat(nodejs20): WEBAPP-30462 Node updated to 20

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/DocFirstPreloader.js
- src/lib/viewers/doc/Document.scss
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/DocFirstPreloader-test.js
When the webp rep comes back with a a non success status such as the response below, the preloader still constructed a webp image url from the template and tried to request it. This returned a 404 which stopped the preloader. The end result was that preloading was essentially disabled in cases such as this when in actuality the jpeg url should be used instead.
```
{
"representation": "webp",
"properties": { ......},
"info": {
"url": "........."
},
"status": {
"state": "error",
"code": "error_large_size_file"
},
"content": {
"url_template": "..........."
}
},
```
Additionally, I updating the positioning of the spinner based on whether or not thumbnail sidebar is open or not.
> fix(doc-first): webp rep is not marked as success bug

- src/lib/constants.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
Based on issues found when migrated to production the following fixes were made
* updating the preloader time diff event to only return the time diff as it's value
* changing the logic so that webp preloading will happen if there is no available jpeg rep but a webp rep is available
* adding/updating test cases 
* being more explicit about Presentations not using the new preloader. While not causing en error, presentations were going down that doc first codepath when the feature was enabled and should not be.
> fix(doc-first): code update

- src/lib/ThumbnailsSidebar.js
- src/lib/__tests__/ThumbnailsSidebar-test.js
- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/DocFirstPreloader.js
- src/lib/viewers/doc/Document.scss
- src/lib/viewers/doc/Presentation.scss
- src/lib/viewers/doc/PresentationPreloader.js
- src/lib/viewers/doc/PresentationViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
- src/lib/viewers/doc/__tests__/DocFirstPreloader-test.js
- src/lib/viewers/doc/__tests__/DocumentViewer-test.js
- src/lib/viewers/doc/__tests__/PresentationViewer-test.js
- src/lib/viewers/doc/_docBase.scss
* Adding doc first preloader to presentations
* renaming retrievedPages to retrievedPagesCount
* updating metrics event logic to only preload time diff data if there are webp representations
* extracting doc first specific css out into the document mixin
> feat(doc-first): adding doc first behavior to presentations

- src/lib/viewers/doc/DocBaseViewer.js
- src/lib/viewers/doc/__tests__/DocBaseViewer-test.js
Removing the doc first pages check. This loadViewerAssets code will only be called from EUA where doc first pages is enabled and including that check here is adding tech debt. The next step will be to consolidate exif reader versions so that only the one for doc first pages is used.
> fix(pdfjs-preload): removing doc first pages check

- src/lib/viewers/controls/media/VolumeControls.scss
- src/lib/viewers/controls/media/VolumeControls.tsx
- src/lib/viewers/controls/media/__tests__/VolumeControls-test.tsx
- src/lib/viewers/controls/slider/VolumeSliderControl.scss
- src/lib/viewers/controls/slider/VolumeSliderControl.tsx
- src/lib/viewers/controls/slider/__tests__/VolumeSliderControl-test.tsx
- src/lib/viewers/media/MediaBaseViewer.js
- src/lib/viewers/media/__tests__/MP3Controls-test.jsx
- src/lib/viewers/media/__tests__/MP4Controls-test.jsx
This PR adds the vertical volume slider to the video controls. The previous volume slider used the same component as the horizontal video playback slider and all of the volume calculations were based on the sliders width. Now those calculations are based on the sliders height. 
PR Notes:
* The slider height is determined based on the volume PR [Reference](https://github.com/box/box-content-preview/pull/1581/files#diff-637ca22bd00a86eb52104d57bfd67e88b359dea42264160a56980b9acf44d7d3R158-R160)
* The  callbacks in the new VolumeSliderControl are the same as in the original [Slider](https://github.com/box/box-content-preview/blob/master/src/lib/viewers/controls/slider/SliderControl.tsx) with the difference being that they use height values instead when they get the mouse position value to …
> feat(video-ui-updates): adding vertical media volume controls.
